'use strict';
/* Cap 100 — grande base de recettes (v1.4).
   Chargé après recipes-data.js. Les valeurs nutritionnelles des ingrédients viennent de la table Ciqual (code « cq »).
   Toutes les recettes sont pour 1 portion ; les féculents sont indiqués CUITS (la liste de courses convertit en poids sec).

   Pour ajouter une recette : copie une ligne X(...) :
   X(identifiant, nom, catégorie, minutes, "tags séparés par des espaces",
     "Ingrédient@grammes; Ingrédient@grammes", "placard|placard", "étape 1|étape 2", "astuce")
   Les noms d'ingrédients doivent correspondre exactement à un aliment de la base (voir D.EXTRA_FOODS). */

/* ---------- Nouveaux ingrédients ---------- */
/* [clé, nom, code Ciqual, rayon, portion, libellé portion, unité d'achat, achat cru/sec, prix €/kg, conditionnement g, longue conservation] */
D.MORE_PRICES = {};
[
  ['allumettes-volaille', 'Allumettes de volaille', 28929, 'vi', 70, '1/2 barquette', { unitG: 150, unit: 'barquette (150 g)', units: 'barquettes (150 g)' }, null, 12, 150],
  ['bacon', 'Filet de bacon', 28727, 'vi', 50, '5 tranches', { unitG: 120, unit: 'paquet (120 g)', units: 'paquets (120 g)' }, null, 18, 120],
  ['pecorino', 'Pecorino', 12122, 'cr', 15, '1 c. à soupe râpé', null, null, 28, 150],
  ['reblochon', 'Reblochon', 12045, 'cr', 40, '1/10 de reblochon', { unitG: 450, unit: 'reblochon', units: 'reblochons' }, null, 14, 450],
  ['endive', 'Endive', 20026, 'fl', 120, '1 endive', { unitG: 120, unit: 'endive', units: 'endives' }, null, 3.5, 0],
  ['mangue', 'Mangue', 13025, 'fl', 100, '1/3 de mangue', { unitG: 300, unit: 'mangue', units: 'mangues' }, null, 6, 0],
  ['chia', 'Graines de chia', 15047, 'ep', 15, '1 c. à soupe', null, null, 12, 250],
  ['bun', 'Pain burger complet', 7262, 'bo', 75, '1 pain', { unitG: 75, unit: 'pain', units: 'pains' }, null, 7, 300],
  ['bagel', 'Bagel', 7258, 'bo', 85, '1 bagel', { unitG: 85, unit: 'bagel', units: 'bagels' }, null, 7, 340],
  ['beurre', 'Beurre doux', 16400, 'cr', 5, '1 noisette', null, null, 10, 250],
  ['cacao', 'Cacao non sucré', 18100, 'ep', 5, '1 c. à café', null, null, 12, 0, true],
  ['boeuf-braise', 'Bœuf braisé (paleron)', 6271, 'vi', 150, '1 portion', null, { name: 'Paleron de bœuf (cru)', factor: 1.45 }, 15, 0],
  ['lentilles-corail', 'Lentilles corail cuites', 20589, 'fe', 150, '1 assiette', null, { name: 'Lentilles corail (sèches)', factor: 0.4 }, 4, 500],
  ['blanc-oeuf', 'Blanc d\'œuf', 22001, 'cr', 60, '2 blancs', null, null, 4, 500],
  ['farine', 'Farine T55', 9436, 'pl', 10, '1 c. à soupe', null, null, 1, 0, true],
  ['gnocchi', 'Gnocchi', 25510, 'fe', 200, '1 assiette', { unitG: 500, unit: 'paquet (500 g)', units: 'paquets (500 g)' }, null, 4, 500],
  ['coulis', 'Coulis de tomate', 20260, 'co', 150, '1/3 de brique', { unitG: 500, unit: 'brique (500 g)', units: 'briques (500 g)' }, null, 2, 500],
  ['tomates-cerises', 'Tomates cerises', 20172, 'fl', 100, '8 tomates cerises', { unitG: 250, unit: 'barquette (250 g)', units: 'barquettes (250 g)' }, null, 7, 250],
  ['sardines', 'Sardines à l\'huile d\'olive', 26040, 'co', 100, '1 boîte égouttée', { unitG: 100, unit: 'boîte', units: 'boîtes' }, null, 14, 100],
  ['riz-complet', 'Riz complet cuit', 9103, 'fe', 150, '1 assiette', null, { name: 'Riz complet (sec)', factor: 0.38 }, 3, 1000],
  ['pates-completes', 'Pâtes complètes cuites', 9871, 'fe', 200, '1 assiette', null, { name: 'Pâtes complètes (sèches)', factor: 0.42 }, 2.4, 500],
  ['haricots-blancs', 'Haricots blancs', 20511, 'co', 130, '1/2 boîte', { unitG: 265, unit: 'boîte (400 g)', units: 'boîtes (400 g)' }, null, 3.5, 265],
  ['tofu-fume', 'Tofu fumé', 20912, 'cr', 100, '1/2 bloc', { unitG: 200, unit: 'bloc (200 g)', units: 'blocs (200 g)' }, null, 12, 200],
  ['kiwi', 'Kiwi', 13021, 'fl', 75, '1 kiwi', { unitG: 75, unit: 'kiwi', units: 'kiwis' }, null, 4, 0],
  ['orange', 'Orange', 13034, 'fl', 150, '1 orange', { unitG: 150, unit: 'orange', units: 'oranges' }, null, 2.5, 0],
  ['fraises', 'Fraises', 13014, 'fl', 150, '1 bol', { unitG: 250, unit: 'barquette (250 g)', units: 'barquettes (250 g)' }, null, 8, 250],
  ['compote', 'Compote sans sucres ajoutés', 13153, 'ep', 100, '1 pot', { unitG: 100, unit: 'pot', units: 'pots' }, null, 3.5, 400],
  ['petit-suisse', 'Petit-suisse 0 %', 19663, 'cr', 60, '1 petit-suisse', { unitG: 60, unit: 'petit-suisse', units: 'petits-suisses' }, null, 4, 360],
  ['mayo-legere', 'Mayonnaise allégée', 11079, 'ep', 10, '1 c. à café bombée', null, null, 6, 0, true],
  ['ketchup', 'Ketchup', 11008, 'ep', 15, '1 c. à soupe', null, null, 4, 0, true],
  ['galette-sarrasin', 'Galette de sarrasin', 23801, 'bo', 60, '1 galette', { unitG: 60, unit: 'galette', units: 'galettes' }, null, 8, 360],
  ['polenta', 'Polenta cuite', 9615, 'fe', 250, '1 assiette', null, { name: 'Polenta (sèche)', factor: 0.22 }, 3, 500],
  ['comte', 'Comté', 12110, 'cr', 20, '1 fine tranche', null, null, 20, 200],
  ['cheddar', 'Cheddar', 12726, 'cr', 20, '1 tranche', { unitG: 20, unit: 'tranche', units: 'tranches' }, null, 12, 200],
  ['sesame', 'Graines de sésame', 15010, 'ep', 5, '1 c. à café', null, null, 10, 0, true],
  ['cajou', 'Noix de cajou', 15054, 'ep', 15, '1 petite poignée', null, null, 20, 200],
  ['gingembre', 'Gingembre frais', 11074, 'fl', 5, '1 cm', null, null, 8, 0],
  ['radis', 'Radis', 20045, 'fl', 60, '6 radis', { unitG: 200, unit: 'botte', units: 'bottes' }, null, 6, 0],
  ['colin', 'Colin (lieu) cuit', 26192, 'vi', 180, '1 filet', null, { name: 'Filet de colin ou lieu (cru)', factor: 1.2 }, 14, 0],
  ['oignon', 'Oignon jaune', 20034, 'fl', 50, '1/2 oignon', { unitG: 100, unit: 'oignon', units: 'oignons' }, null, 2, 0]
].forEach(([k, name, cq, aisle, portion, portionLabel, unit, buy, price, pack, stock]) => {
  D.EXTRA_FOODS.push({ id: 'ing-' + k, name, cq, kcal: 0, p: 0, c: 0, f: 0, portion, portionLabel, base: true, aisle, ...(unit || {}), ...(buy ? { buy } : {}) });
  D.MORE_PRICES[name] = [price, pack, !!stock];
});

/* ---------- Catégories ---------- */
D.RECIPE_CATS.find(c => c.id === 'wrap').label = 'Wraps & sandwichs';
D.RECIPE_CATS.splice(D.RECIPE_CATS.findIndex(c => c.id === 'bowl'), 0, { id: 'pates', label: 'Pâtes', icon: 'pasta' });
D.RECIPE_CATS.splice(D.RECIPE_CATS.findIndex(c => c.id === 'petitdej'), 0, { id: 'soupe', label: 'Soupes', icon: 'soup' });

/* ---------- Écriture compacte ---------- */
const X = (id, name, cat, time, tags, ing, pantry, steps, tip) => ({
  id: 'r-' + id, name, cat, time, tags: tags ? tags.split(' ') : [],
  ing: ing.split(';').map(s => { const [n, g] = s.split('@'); return R_(n.trim(), +g); }),
  pantry: pantry ? pantry.split('|') : [], steps: steps.split('|'), tip
});

D.BASE_RECIPES.push(
  /* ====================== PÂTES ====================== */
  X('pa-carbo', "Carbonara authentique allégée (sans crème)", 'pates', 20, 'lunchbox',
    "Pâtes cuites@200; Œuf entier@60; Filet de bacon@60; Pecorino@15",
    "Poivre noir|Gros sel pour l'eau",
    "Fais cuire 85 g de spaghetti secs dans une grande casserole d'eau salée. Garde une tasse d'eau de cuisson avant d'égoutter.|Pendant ce temps, coupe le bacon en lanières et fais-le dorer sans matière grasse.|Dans un bol, bats l'œuf avec le pecorino râpé et beaucoup de poivre.|Hors du feu, verse les pâtes égouttées dans la poêle du bacon, puis l'œuf et 3 à 4 c. à soupe d'eau de cuisson. Mélange vivement : la sauce devient crémeuse grâce à l'amidon, sans cuire l'œuf.",
    "La vraie carbonara ne contient pas de crème : c'est l'œuf, le fromage et l'eau de cuisson qui font la sauce. Le filet de bacon remplace le guanciale ou les lardons, avec près de 8 fois moins de gras."),
  X('pa-carbo-skyr', "Carbonara protéinée au skyr", 'pates', 20, 'lunchbox',
    "Pâtes cuites@200; Allumettes de volaille@70; Œuf entier@60; Skyr nature@60; Parmesan@15",
    "Poivre noir|Ail (facultatif)",
    "Cuis 85 g de pâtes sèches al dente, garde un demi-verre d'eau de cuisson.|Fais revenir les allumettes de volaille 3 min sans matière grasse.|Mélange au fouet l'œuf, le skyr, le parmesan et le poivre jusqu'à obtenir une crème lisse.|Coupe le feu, attends 30 secondes, ajoute les pâtes puis la crème au skyr et 2 à 3 c. à soupe d'eau de cuisson. Mélange sans remettre sur le feu.",
    "Le skyr apporte du crémeux et environ 5 g de protéines de plus que la même quantité de crème. Il doit être ajouté hors du feu : chauffé, il tourne et fait des grumeaux."),
  X('pa-carbo-courgette', "Carbonara moitié pâtes, moitié courgettes", 'pates', 20, '',
    "Pâtes cuites@120; Courgette cuite@200; Œuf entier@60; Filet de bacon@60; Pecorino@15",
    "Poivre noir",
    "Taille la courgette en longs rubans ou en tagliatelles avec un économe.|Cuis 50 g de spaghetti secs ; ajoute les rubans de courgette dans l'eau pendant les 60 dernières secondes.|Dore le bacon, bats l'œuf avec le pecorino et le poivre.|Hors du feu, mélange pâtes, courgettes, bacon, œuf et un peu d'eau de cuisson.",
    "Même assiette pleine, environ 100 kcal de moins : les courgettes prennent le goût de la sauce."),
  X('pa-carbo-poulet', "Carbonara poulet & champignons", 'pates', 25, 'lunchbox',
    "Pâtes cuites@180; Blanc de poulet cuit@100; Champignons de Paris@100; Œuf entier@60; Parmesan@15",
    "Ail|Persil|Poivre",
    "Cuis 75 g de pâtes sèches et garde un peu d'eau de cuisson.|Fais sauter les champignons émincés et le poulet en dés avec l'ail.|Bats l'œuf avec le parmesan et le poivre.|Hors du feu, réunis tout avec 3 c. à soupe d'eau de cuisson et mélange vivement. Parsème de persil.",
    "Version complète en une assiette : protéines du poulet et de l'œuf, légumes, féculent."),
  X('pa-carbo-blancs', "Carbonara complète « volume » aux blancs d'œufs", 'pates', 20, '',
    "Pâtes complètes cuites@200; Œuf entier@60; Blanc d'œuf@60; Filet de bacon@50; Pecorino@15",
    "Poivre noir",
    "Cuis 85 g de pâtes complètes sèches, garde de l'eau de cuisson.|Dore le bacon en lanières.|Fouette l'œuf entier, les blancs, le pecorino et le poivre.|Hors du feu, mélange le tout avec l'eau de cuisson jusqu'à obtenir une sauce nappante.",
    "Les blancs augmentent la quantité de sauce et les protéines pour seulement 30 kcal ; les pâtes complètes apportent plus de fibres."),
  X('pa-carbo-vege', "Carbonara végétarienne au tofu fumé & poireaux", 'pates', 25, 'vege',
    "Pâtes cuites@200; Tofu fumé@80; Poireau@80; Œuf entier@60; Parmesan@15",
    "Poivre noir",
    "Émince le poireau et fais-le fondre 5 min avec un filet d'eau.|Coupe le tofu fumé en petits dés et fais-le dorer.|Bats l'œuf avec le parmesan et le poivre.|Hors du feu, mélange pâtes, poireau, tofu, œuf et un peu d'eau de cuisson.",
    "Le tofu fumé donne le goût fumé des lardons, avec des protéines végétales."),
  X('pa-carbo-gnocchi', "Gnocchi façon carbonara & petits pois", 'pates', 15, '',
    "Gnocchi@200; Allumettes de volaille@60; Petits pois@80; Œuf entier@60; Parmesan@15",
    "Poivre noir",
    "Cuis les gnocchi 2 min dans l'eau bouillante avec les petits pois. Garde un peu d'eau.|Dore les allumettes de volaille.|Bats l'œuf avec le parmesan et le poivre.|Hors du feu, mélange tout avec 2 c. à soupe d'eau de cuisson.",
    "Prêt en 15 minutes, idéal les soirs de flemme."),
  X('pa-onepot-jambon', "One-pot pâtes jambon, petits pois & parmesan", 'pates', 20, 'lunchbox',
    "Pâtes cuites@180; Jambon blanc@60; Petits pois@80; Fromage frais allégé@25; Parmesan@10",
    "Bouillon cube|Poivre",
    "Dans une sauteuse, mets 75 g de pâtes sèches, les petits pois et 250 ml d'eau avec un demi-cube de bouillon.|Cuis à couvert en remuant, jusqu'à absorption du liquide (10 à 12 min).|Hors du feu, ajoute le fromage frais, le jambon en lanières et le parmesan.",
    "Une seule casserole à laver : parfait pour une gamelle."),
  X('pa-saumon-epinards', "Penne saumon, épinards & citron", 'pates', 20, 'lunchbox',
    "Pâtes cuites@180; Saumon cuit@100; Épinards frais@80; Fromage frais allégé@30; Citron (jus)@10",
    "Ail|Aneth|Poivre",
    "Cuis 75 g de penne sèches.|Fais tomber les épinards à la poêle avec l'ail.|Ajoute le saumon émietté, le fromage frais, le citron et 2 c. à soupe d'eau de cuisson.|Mélange avec les pâtes, poivre et aneth.",
    "Le saumon apporte des oméga-3, bons pour la récupération."),
  X('pa-thon-tomate', "Spaghetti thon, tomate & olives (puttanesca légère)", 'pates', 20, 'lunchbox',
    "Pâtes cuites@200; Thon au naturel@100; Coulis de tomate@150; Olives noires@15; Parmesan@5",
    "Ail|Câpres|Piment (facultatif)",
    "Cuis 85 g de spaghetti secs.|Fais revenir l'ail, ajoute le coulis, les olives et quelques câpres, laisse mijoter 8 min.|Ajoute le thon égoutté en fin de cuisson.|Mélange avec les pâtes, parsème de parmesan.",
    "Tout vient du placard : c'est le plat de dépannage parfait."),
  X('pa-pesto-poulet', "Pâtes pesto, poulet & tomates cerises", 'pates', 20, 'lunchbox',
    "Pâtes cuites@180; Blanc de poulet cuit@120; Pesto@15; Tomates cerises@100; Parmesan@5",
    "Basilic",
    "Cuis 75 g de pâtes sèches.|Dore le poulet en dés, ajoute les tomates cerises coupées en deux 2 min.|Hors du feu, mélange pâtes, poulet, tomates, pesto et 2 c. à soupe d'eau de cuisson.",
    "Une seule cuillère de pesto suffit si tu la détends avec l'eau de cuisson."),
  X('pa-arrabbiata', "Penne all'arrabbiata au poulet & mozzarella", 'pates', 20, '',
    "Pâtes cuites@200; Coulis de tomate@150; Blanc de poulet cuit@100; Mozzarella@40",
    "Ail|Piment|Basilic",
    "Cuis 85 g de penne sèches.|Fais revenir l'ail et le piment, ajoute le coulis et laisse réduire 10 min.|Ajoute le poulet en dés et les pâtes.|Sers avec la mozzarella déchirée par-dessus.",
    "Le piment est un bon moyen d'avoir du goût sans matière grasse."),
  X('pa-bolo-lentilles', "Bolognaise de lentilles corail", 'pates', 30, 'vege batch',
    "Pâtes cuites@180; Lentilles corail cuites@120; Coulis de tomate@150; Carottes@60; Oignon jaune@30; Parmesan@10",
    "Ail|Herbes de Provence",
    "Fais revenir oignon, ail et carotte râpée 5 min.|Ajoute 50 g de lentilles corail sèches, le coulis et 150 ml d'eau ; cuis 15 min.|Sers sur 75 g de pâtes sèches cuites, avec le parmesan.",
    "Les lentilles corail fondent et imitent la texture de la viande hachée, avec des fibres en plus."),
  X('pa-onepot-poulet', "One-pot pâtes poulet, tomate & épinards", 'pates', 20, 'lunchbox batch',
    "Pâtes cuites@180; Blanc de poulet cuit@120; Tomates concassées (boîte)@150; Épinards frais@60; Fromage frais allégé@20",
    "Ail|Paprika|Bouillon cube",
    "Dans une sauteuse, mets 75 g de pâtes sèches, les tomates, l'ail, le paprika, un demi-cube et 200 ml d'eau.|Cuis 10 à 12 min en remuant.|Ajoute le poulet, les épinards et le fromage frais les 2 dernières minutes.",
    "Se multiplie facilement par 4 pour les gamelles de la semaine."),
  X('pa-ricotta', "Pâtes ricotta, épinards & jambon", 'pates', 20, '',
    "Pâtes cuites@180; Ricotta@60; Épinards frais@80; Jambon blanc@60; Parmesan@5",
    "Muscade|Poivre",
    "Cuis 75 g de pâtes sèches.|Fais tomber les épinards 2 min.|Mélange la ricotta avec 3 c. à soupe d'eau de cuisson, la muscade et le poivre.|Ajoute pâtes, épinards et jambon en lanières.",
    "La ricotta fait une sauce crémeuse deux fois moins grasse qu'une crème entière."),
  X('pa-crevettes-ail', "Linguine crevettes, ail & citron", 'pates', 15, '',
    "Pâtes cuites@200; Crevettes cuites@150; Tomates cerises@80; Huile d'olive@5; Citron (jus)@10",
    "Ail|Persil|Piment",
    "Cuis 85 g de linguine sèches.|Fais revenir l'ail dans l'huile, ajoute les tomates cerises 2 min puis les crevettes 1 min.|Ajoute les pâtes, le citron, le persil et un peu d'eau de cuisson.",
    "Les crevettes sont très riches en protéines et presque sans gras."),
  X('pa-champignons-creme', "Tagliatelles poulet-champignons, crème légère", 'pates', 20, '',
    "Pâtes cuites@180; Blanc de poulet cuit@120; Champignons de Paris@120; Crème légère 15 %@30; Parmesan@5",
    "Ail|Persil",
    "Cuis 75 g de tagliatelles sèches.|Fais dorer poulet et champignons émincés avec l'ail.|Ajoute la crème et 3 c. à soupe d'eau de cuisson, laisse épaissir 1 min.|Mélange avec les pâtes, parmesan et persil.",
    "30 g de crème légère suffisent quand on la détend avec l'eau de cuisson."),
  X('pa-brocoli', "Pâtes brocoli, poulet & parmesan", 'pates', 20, 'lunchbox',
    "Pâtes cuites@160; Blanc de poulet cuit@120; Brocoli cuit@150; Parmesan@10; Huile d'olive@5",
    "Ail|Citron|Piment",
    "Cuis 65 g de pâtes sèches avec les fleurettes de brocoli dans la même eau.|Fais revenir l'ail dans l'huile, ajoute le poulet.|Mélange avec pâtes, brocoli, parmesan et un zeste de citron.",
    "Le brocoli cuit avec les pâtes : une casserole en moins."),
  X('pa-lasagnes', "Lasagnes allégées bœuf & courgettes", 'pates', 60, 'batch',
    "Pâtes cuites@150; Steak haché 5 % (cuit)@120; Coulis de tomate@150; Courgette cuite@100; Fromage blanc 0 %@80; Emmental@15",
    "Oignon|Ail|Herbes de Provence|Muscade",
    "Fais revenir oignon, ail et bœuf haché, ajoute le coulis et les courgettes en dés, mijote 10 min.|Mélange le fromage blanc avec la muscade : il remplace la béchamel.|Alterne dans un plat : feuilles de lasagnes, sauce bolognaise, fromage blanc. Termine par l'emmental.|40 min au four à 180 °C.",
    "Le fromage blanc à la place de la béchamel économise environ 100 kcal par part."),
  X('pa-mac-cottage', "Mac & cheese protéiné au cottage cheese", 'pates', 20, '',
    "Pâtes cuites@180; Cottage cheese@120; Cheddar@20; Jambon blanc@40; Brocoli cuit@100",
    "Moutarde|Paprika fumé",
    "Cuis 75 g de coquillettes sèches et le brocoli.|Mixe le cottage cheese avec le cheddar, une pointe de moutarde et 3 c. à soupe d'eau de cuisson.|Chauffe doucement la sauce, ajoute pâtes, brocoli et jambon. Paprika fumé sur le dessus.",
    "Le cottage cheese mixé donne une sauce fromagère bien plus riche en protéines qu'une béchamel."),
  X('pa-boulettes', "Pâtes aux boulettes de bœuf, sauce tomate", 'pates', 30, 'batch',
    "Pâtes cuites@180; Steak haché 5 % (cuit)@120; Coulis de tomate@150; Parmesan@10",
    "Ail|Origan|Oignon",
    "Façonne de petites boulettes avec le bœuf haché cru, l'ail et l'origan.|Dore-les à la poêle, ajoute le coulis et laisse mijoter 12 min.|Sers avec 75 g de pâtes sèches cuites et le parmesan.",
    "Prépare le double de boulettes : elles se congèlent très bien."),
  X('pa-thon-courgette', "Pâtes complètes thon, courgette & citron", 'pates', 20, 'lunchbox',
    "Pâtes complètes cuites@180; Thon au naturel@100; Courgette cuite@150; Fromage frais allégé@20; Citron (jus)@10",
    "Ail|Basilic",
    "Cuis 75 g de pâtes complètes sèches.|Fais sauter la courgette en dés avec l'ail 6 min.|Ajoute le thon, le fromage frais, le citron et les pâtes.",
    "Se mange chaud ou froid en lunchbox."),
  X('pa-gnocchi-tomate', "Gnocchi poêlés, tomates cerises, mozzarella & dinde", 'pates', 15, '',
    "Gnocchi@200; Tomates cerises@120; Mozzarella@50; Blanc de dinde (tranches)@60",
    "Basilic|Ail",
    "Poêle les gnocchi à sec 6 à 8 min jusqu'à ce qu'ils dorent (sans les cuire à l'eau).|Ajoute l'ail et les tomates cerises 3 min.|Hors du feu, ajoute la dinde en lanières, la mozzarella et le basilic.",
    "Poêlés, les gnocchi deviennent croustillants dehors et fondants dedans."),
  X('pa-saumon-fume', "Pâtes saumon fumé & fromage frais", 'pates', 15, '',
    "Pâtes cuites@180; Saumon fumé@60; Fromage frais allégé@40; Épinards frais@50; Citron (jus)@5",
    "Aneth|Poivre",
    "Cuis 75 g de pâtes sèches.|Dans la casserole chaude, mélange le fromage frais avec 3 c. à soupe d'eau de cuisson.|Ajoute pâtes, épinards, saumon fumé en lanières, citron et aneth.",
    "Le saumon fumé est salé : inutile de saler l'eau des pâtes."),
  X('pa-sardines', "Pâtes aux sardines, citron & tomates cerises", 'pates', 15, '',
    "Pâtes cuites@180; Sardines à l'huile d'olive@100; Tomates cerises@100; Citron (jus)@10",
    "Ail|Persil|Piment|Chapelure (facultatif)",
    "Cuis 75 g de pâtes sèches.|Fais revenir l'ail et les tomates cerises, ajoute les sardines émiettées.|Mélange avec les pâtes, le citron et le persil.",
    "Les sardines en boîte sont l'une des sources d'oméga-3 les moins chères."),
  X('pa-alfredo', "Pâtes « alfredo » au fromage blanc & poulet", 'pates', 20, '',
    "Pâtes cuites@180; Blanc de poulet cuit@120; Fromage blanc 0 %@100; Parmesan@15; Brocoli cuit@100",
    "Ail|Muscade|Poivre",
    "Cuis 75 g de fettuccine sèches et le brocoli.|Hors du feu, mélange le fromage blanc, le parmesan, l'ail râpé et 3 c. à soupe d'eau de cuisson.|Ajoute pâtes, poulet et brocoli, poivre et muscade.",
    "Comme le skyr, le fromage blanc s'ajoute hors du feu pour ne pas trancher."),
  X('pa-curry-coco', "Pâtes au poulet, curry & lait de coco", 'pates', 20, '',
    "Pâtes cuites@180; Blanc de poulet cuit@120; Lait de coco léger@60; Petits pois@80; Oignon jaune@30",
    "Curry en poudre|Gingembre",
    "Cuis 75 g de pâtes sèches.|Fais revenir l'oignon, le curry et le poulet.|Ajoute le lait de coco et les petits pois, laisse épaissir 3 min.|Mélange avec les pâtes.",
    "Une sauce douce et parfumée pour changer de la tomate."),
  X('pa-haricots', "Pâtes aux haricots blancs, épinards & tomate", 'pates', 20, 'vege lunchbox',
    "Pâtes cuites@150; Haricots blancs@120; Épinards frais@80; Coulis de tomate@100; Parmesan@10",
    "Ail|Romarin",
    "Cuis 60 g de pâtes sèches.|Fais revenir l'ail et le romarin, ajoute le coulis et les haricots rincés 5 min.|Ajoute les épinards, puis les pâtes et le parmesan.",
    "Pâtes + légumineuses : un duo classique italien, rassasiant et bon marché."),
  X('pa-gratin-brocoli', "Gratin de pâtes brocoli & poulet", 'pates', 35, 'batch',
    "Pâtes cuites@150; Brocoli cuit@120; Blanc de poulet cuit@100; Lait demi-écrémé@60; Fromage frais allégé@20; Emmental@20",
    "Muscade",
    "Cuis 60 g de pâtes sèches et le brocoli.|Mélange le lait et le fromage frais avec la muscade.|Dans un plat : pâtes, brocoli, poulet, la sauce, puis l'emmental.|20 min au four à 200 °C.",
    "Un gratin de pâtes réconfortant qui reste raisonnable."),

  /* ====================== BOWLS & RIZ ====================== */
  X('bw-burrito', "Burrito bowl au poulet", 'bowl', 20, 'lunchbox',
    "Riz basmati cuit@150; Blanc de poulet cuit@120; Haricots rouges cuits@80; Maïs doux (boîte)@40; Tomate@80; Yaourt nature 0 %@30; Avocat@30",
    "Cumin|Paprika|Citron vert",
    "Assaisonne le poulet de cumin et paprika, dore-le.|Chauffe les haricots rouges rincés.|Dans un bol : riz, poulet, haricots, maïs, tomate en dés, avocat et une cuillère de yaourt citronné.",
    "Tout le goût d'un burrito, sans la tortilla ni le fromage fondu."),
  X('bw-cantonais', "Riz cantonais protéiné", 'bowl', 20, 'lunchbox',
    "Riz basmati cuit@180; Œuf entier@60; Jambon blanc@60; Petits pois@60; Crevettes cuites@60; Sauce soja@10",
    "Oignon vert|Huile neutre",
    "Idéalement, utilise du riz cuit la veille.|Brouille l'œuf dans une poêle chaude puis réserve.|Saute le riz, les petits pois, le jambon en dés et les crevettes 5 min.|Ajoute l'œuf et la sauce soja.",
    "Le riz de la veille ne colle pas : c'est le secret du riz sauté."),
  X('bw-thon-mangue', "Bowl thon, edamame & mangue", 'bowl', 15, 'froid lunchbox',
    "Riz basmati cuit@150; Thon au naturel@110; Edamame surgelés@60; Mangue@60; Concombre@60; Sauce soja@10; Graines de sésame@3",
    "Vinaigre de riz",
    "Décongèle les edamame 3 min dans l'eau bouillante.|Assaisonne le riz d'un filet de vinaigre de riz.|Dispose riz, thon, edamame, mangue et concombre en dés. Sauce soja et sésame.",
    "Version poke bowl économique avec du thon en boîte."),
  X('bw-bibimbap', "Bibimbap express au bœuf", 'bowl', 20, '',
    "Riz basmati cuit@170; Steak haché 5 % (cuit)@120; Œuf entier@60; Épinards frais@60; Carottes@60; Sauce soja@10",
    "Ail|Piment (gochujang ou sriracha)|Graines de sésame",
    "Fais revenir le bœuf haché avec l'ail et la sauce soja.|Fais tomber les épinards 1 min ; râpe la carotte.|Cuis un œuf au plat.|Dans un bol : riz, bœuf, légumes et l'œuf au centre. Piment à volonté.",
    "Crève le jaune et mélange tout : il fait office de sauce."),
  X('bw-quinoa-patate', "Bowl poulet, quinoa & patate douce rôtie", 'bowl', 35, 'lunchbox batch',
    "Quinoa cuit@120; Blanc de poulet cuit@120; Patate douce cuite@150; Épinards frais@40; Yaourt nature 0 %@30",
    "Paprika|Cumin|Citron",
    "Rôtis la patate douce en cubes 25 min à 200 °C avec paprika et cumin.|Cuis 45 g de quinoa sec.|Assemble avec le poulet, les jeunes pousses et une sauce yaourt-citron.",
    "Prépare 3 bowls à la fois : ils se gardent 3 jours au frais."),
  X('bw-crevettes-brocoli', "Riz sauté crevettes, brocoli & gingembre", 'bowl', 20, '',
    "Riz basmati cuit@160; Crevettes cuites@150; Brocoli cuit@150; Gingembre frais@5; Sauce soja@10",
    "Ail|Huile neutre",
    "Fais sauter le brocoli 3 min à feu vif avec l'ail et le gingembre râpé.|Ajoute le riz puis les crevettes, et la sauce soja.",
    "Riche en protéines et très peu gras."),
  X('bw-mexicain-vege', "Bowl mexicain végétarien", 'bowl', 15, 'vege lunchbox',
    "Riz complet cuit@150; Haricots rouges cuits@120; Maïs doux (boîte)@50; Poivron@80; Avocat@40; Yaourt nature 0 %@30; Feta@20",
    "Cumin|Citron vert|Coriandre",
    "Fais sauter le poivron en lanières avec le cumin.|Chauffe les haricots rincés.|Assemble avec le riz, le maïs, l'avocat, la feta émiettée et le yaourt citronné.",
    "Haricots + riz : l'association donne des protéines complètes."),
  X('bw-tofu', "Bowl tofu fumé, riz complet & légumes", 'bowl', 20, 'vege',
    "Riz complet cuit@150; Tofu fumé@120; Brocoli cuit@100; Carottes@60; Sauce soja@10; Graines de sésame@3",
    "Gingembre|Miel (facultatif)",
    "Dore le tofu en cubes à la poêle.|Cuis le brocoli, râpe la carotte.|Assemble, arrose de sauce soja et parsème de sésame.",
    "Le tofu fumé n'a pas besoin de marinade : il a déjà du goût."),
  X('bw-dahl', "Dahl de lentilles corail & riz", 'bowl', 30, 'vege batch',
    "Lentilles corail cuites@200; Riz basmati cuit@120; Lait de coco léger@50; Épinards frais@60; Tomates concassées (boîte)@100; Oignon jaune@40",
    "Curry|Curcuma|Cumin|Gingembre|Ail",
    "Fais revenir oignon, ail, gingembre et épices.|Ajoute 80 g de lentilles corail sèches, les tomates, le lait de coco et 300 ml d'eau ; cuis 20 min.|Ajoute les épinards à la fin. Sers avec le riz.",
    "Plat complet végétarien, très économique : environ 1,50 € la portion."),
  X('bw-boulgour-houmous', "Bowl méditerranéen boulgour, poulet & houmous", 'bowl', 15, 'lunchbox',
    "Boulgour cuit@150; Blanc de poulet cuit@120; Houmous@30; Concombre@80; Tomates cerises@80",
    "Menthe|Citron|Paprika",
    "Cuis 55 g de boulgour sec.|Assaisonne le poulet de paprika et dore-le.|Assemble avec concombre, tomates, houmous et menthe.",
    "Le houmous joue le rôle de sauce : pas besoin d'huile en plus."),
  X('bw-saumon-avocat', "Bowl saumon, riz complet & avocat", 'bowl', 20, '',
    "Riz complet cuit@150; Saumon cuit@120; Avocat@40; Concombre@60; Edamame surgelés@40; Sauce soja@10",
    "Sésame|Vinaigre de riz",
    "Cuis le saumon 10 min au four ou à la poêle.|Assemble avec le riz, l'avocat, le concombre et les edamame.",
    "Riche en bonnes graisses : garde une portion d'avocat raisonnable."),
  X('bw-dinde-semoule', "Bowl dinde, semoule & légumes rôtis", 'bowl', 30, 'lunchbox',
    "Semoule cuite@150; Escalope de dinde cuite@150; Courgette cuite@100; Poivron@80; Yaourt nature 0 %@30",
    "Ras el hanout|Menthe|Citron",
    "Rôtis courgette et poivron en dés 20 min à 200 °C avec le ras el hanout.|Poêle la dinde.|Sers sur la semoule avec une sauce yaourt-menthe.",
    "La semoule se prépare en 5 minutes à l'eau bouillante."),
  X('bw-nouilles-boeuf', "Nouilles sautées bœuf & poivrons", 'bowl', 20, '',
    "Nouilles de riz cuites@180; Steak haché 5 % (cuit)@120; Poivron@100; Oignon jaune@40; Sauce soja@15",
    "Ail|Gingembre|Piment",
    "Réhydrate 70 g de nouilles de riz sèches.|Saute le bœuf, l'oignon et le poivron à feu vif.|Ajoute les nouilles, l'ail, le gingembre et la sauce soja.",
    "Cuisson à feu vif et rapide : les légumes restent croquants."),
  X('bw-buddha', "Buddha bowl pois chiches rôtis", 'bowl', 30, 'vege lunchbox',
    "Quinoa cuit@120; Pois chiches cuits@120; Patate douce cuite@120; Chou rouge@50; Houmous@20; Épinards frais@30",
    "Paprika fumé|Cumin|Citron",
    "Rôtis pois chiches et patate douce 25 min à 200 °C avec les épices.|Assemble avec le quinoa, le chou rouge émincé et les pousses d'épinards.|Houmous détendu au citron en sauce.",
    "Très rassasiant grâce aux fibres."),
  X('bw-crevettes-mangue', "Bowl crevettes, mangue & avocat", 'bowl', 15, 'froid',
    "Riz basmati cuit@150; Crevettes cuites@130; Mangue@70; Avocat@40; Concombre@60",
    "Citron vert|Coriandre|Piment",
    "Coupe mangue, avocat et concombre en dés.|Assemble avec le riz et les crevettes, arrose de citron vert.",
    "Frais et rapide pour les jours chauds."),
  X('bw-polenta', "Polenta crémeuse, champignons & œuf", 'bowl', 20, 'vege',
    "Polenta cuite@250; Champignons de Paris@150; Œuf entier@60; Parmesan@10; Épinards frais@60",
    "Ail|Thym",
    "Cuis 55 g de polenta sèche dans 4 fois son volume d'eau salée, en remuant.|Poêle champignons et épinards avec ail et thym.|Sers la polenta avec le parmesan, les légumes et un œuf mollet ou poché.",
    "La polenta est un féculent léger quand elle est cuite à l'eau."),
  X('bw-teriyaki-saumon', "Bowl saumon teriyaki maison & brocoli", 'bowl', 20, '',
    "Riz basmati cuit@150; Saumon cuit@120; Brocoli cuit@120; Sauce soja@15; Miel@5",
    "Gingembre|Ail|Sésame",
    "Mélange sauce soja, miel, ail et gingembre.|Poêle le saumon 3 min par face, ajoute la sauce et laisse caraméliser.|Sers avec le riz et le brocoli vapeur.",
    "Une sauce teriyaki maison contient bien moins de sucre que celle du commerce."),

  /* ====================== PLATS ====================== */
  X('pl-basquaise', "Poulet basquaise & riz", 'plat', 35, 'batch lunchbox',
    "Blanc de poulet cuit@130; Riz basmati cuit@160; Poivron@120; Tomates concassées (boîte)@120; Oignon jaune@40",
    "Ail|Piment d'Espelette|Thym",
    "Dore le poulet en morceaux, réserve.|Fais fondre oignon et poivrons 10 min, ajoute tomates, ail et épices.|Remets le poulet, mijote 15 min. Sers avec le riz.",
    "Encore meilleur réchauffé le lendemain."),
  X('pl-poulet-roti', "Cuisse de poulet rôtie, pommes de terre & haricots verts", 'plat', 50, '',
    "Cuisse de poulet rôtie@150; Pomme de terre cuite@200; Haricots verts@150",
    "Thym|Ail|Paprika",
    "Rôtis la cuisse 40 min à 200 °C avec thym et paprika, les pommes de terre en quartiers autour.|Cuis les haricots verts à la vapeur.|Retire la peau du poulet avant de manger.",
    "Enlever la peau du poulet économise environ 80 kcal."),
  X('pl-poulet-moutarde', "Émincé de poulet à la moutarde & riz", 'plat', 20, '',
    "Blanc de poulet cuit@130; Crème légère 15 %@20; Moutarde@10; Riz basmati cuit@150; Haricots verts@150",
    "Estragon|Échalote",
    "Dore le poulet émincé avec l'échalote.|Ajoute la moutarde, la crème et un peu d'eau, laisse napper 2 min.|Sers avec le riz et les haricots verts.",
    "Un classique de bistrot en version légère."),
  X('pl-tikka', "Poulet tikka au yaourt & riz", 'plat', 30, 'lunchbox',
    "Blanc de poulet cuit@140; Yaourt nature 0 %@60; Tomates concassées (boîte)@100; Riz basmati cuit@150; Épinards frais@50",
    "Garam masala|Curcuma|Ail|Gingembre",
    "Fais mariner le poulet dans le yaourt et les épices (15 min minimum).|Dore-le, ajoute les tomates et laisse mijoter 10 min.|Ajoute les épinards. Sers avec le riz.",
    "La marinade au yaourt attendrit la viande sans ajouter de gras."),
  X('pl-poulet-citron', "Poulet citron-gingembre, riz & brocoli", 'plat', 25, '',
    "Blanc de poulet cuit@130; Riz basmati cuit@150; Brocoli cuit@150; Citron (jus)@15; Gingembre frais@5; Miel@5",
    "Ail|Sauce soja",
    "Fais dorer le poulet en dés.|Ajoute citron, gingembre râpé, miel et une cuillère de sauce soja : laisse laquer 2 min.|Sers avec le riz et le brocoli.",
    "Acide et sucré à la fois, sans sauce industrielle."),
  X('pl-poulet-paprika', "Poulet au paprika & pommes de terre rôties", 'plat', 40, 'batch',
    "Blanc de poulet cuit@140; Pomme de terre cuite@220; Poivron@100; Huile d'olive@5",
    "Paprika fumé|Ail|Oignon",
    "Mélange pommes de terre en cubes, poivron et poulet avec l'huile et le paprika.|Étale sur une plaque, 30 min à 210 °C en remuant à mi-cuisson.",
    "Tout cuit sur une seule plaque : zéro vaisselle."),
  X('pl-brochettes', "Brochettes de poulet, semoule & tzatziki", 'plat', 30, '',
    "Blanc de poulet cuit@150; Semoule cuite@150; Yaourt nature 0 %@60; Concombre@60; Tomate@80",
    "Ail|Menthe|Citron|Origan",
    "Fais mariner le poulet en cubes avec citron, ail et origan, puis enfile sur des brochettes.|Grille 10 à 12 min.|Tzatziki : yaourt, concombre râpé, ail, menthe. Sers avec la semoule et la tomate.",
    "Le tzatziki maison au yaourt 0 % : moins de 30 kcal la portion."),
  X('pl-dinde-panee', "Escalope de dinde panée au four & purée de patate douce", 'plat', 35, '',
    "Escalope de dinde cuite@150; Œuf entier@20; Pain de mie complet@20; Patate douce cuite@200; Haricots verts@100",
    "Paprika|Farine",
    "Mixe le pain en chapelure. Passe l'escalope dans l'œuf battu puis la chapelure.|Cuis au four 18 min à 200 °C.|Écrase la patate douce cuite avec un peu de lait ou d'eau de cuisson.",
    "Panure au four au lieu de la poêle : tout le croustillant, sans l'huile."),
  X('pl-dinde-curry', "Dinde au curry coco & riz", 'plat', 25, 'lunchbox',
    "Escalope de dinde cuite@140; Lait de coco léger@60; Oignon jaune@40; Poivron@80; Riz basmati cuit@150",
    "Curry|Gingembre|Coriandre",
    "Fais revenir oignon et poivron, ajoute la dinde en lanières et le curry.|Verse le lait de coco, mijote 8 min.|Sers avec le riz.",
    "Le lait de coco léger contient près de 3 fois moins de gras que le classique."),
  X('pl-steak-puree', "Steak haché, purée maison & haricots verts", 'plat', 25, '',
    "Steak haché 5 % (cuit)@125; Pomme de terre cuite@200; Lait demi-écrémé@50; Haricots verts@150",
    "Muscade|Sel, poivre",
    "Cuis les pommes de terre à l'eau, écrase-les avec le lait chaud et la muscade.|Cuis les haricots verts.|Poêle le steak 2 à 3 min par face.",
    "La purée au lait, sans beurre, reste très onctueuse."),
  X('pl-boeuf-carottes', "Bœuf-carottes mijoté", 'plat', 150, 'batch',
    "Bœuf braisé (paleron)@150; Carottes@200; Pomme de terre cuite@150; Oignon jaune@40",
    "Bouillon cube|Thym|Laurier",
    "Fais dorer le bœuf en cubes, ajoute l'oignon.|Couvre d'eau avec le bouillon, thym et laurier, mijote 1 h 30.|Ajoute carottes et pommes de terre, poursuis 40 min.",
    "Une grosse cocotte le dimanche = 4 repas prêts."),
  X('pl-bourguignon', "Bœuf bourguignon allégé", 'plat', 180, 'batch',
    "Bœuf braisé (paleron)@150; Champignons de Paris@100; Carottes@100; Pomme de terre cuite@150; Oignon jaune@40",
    "Vin rouge (facultatif)|Bouillon cube|Thym|Laurier",
    "Fais dorer le bœuf en cubes et l'oignon.|Mouille avec du bouillon (et un verre de vin si tu veux), ajoute herbes et carottes, mijote 2 h 30.|Ajoute les champignons les 20 dernières minutes. Sers avec les pommes de terre.",
    "Pas de lardons ni de beurre : le mijotage suffit à donner du goût."),
  X('pl-boulettes-semoule', "Boulettes de bœuf à la tomate & semoule", 'plat', 30, 'batch lunchbox',
    "Steak haché 5 % (cuit)@130; Coulis de tomate@150; Semoule cuite@150; Courgette cuite@100",
    "Cumin|Coriandre|Ail",
    "Forme des boulettes avec la viande crue, le cumin et l'ail.|Dore-les, ajoute le coulis et la courgette en dés, mijote 15 min.|Sers sur la semoule.",
    "Une version légère des boulettes à l'orientale."),
  X('pl-kefta', "Kefta de bœuf, boulgour & sauce yaourt", 'plat', 25, '',
    "Steak haché 5 % (cuit)@130; Boulgour cuit@150; Yaourt nature 0 %@50; Oignon rouge@20; Tomate@80",
    "Cumin|Coriandre|Menthe|Paprika",
    "Mélange la viande crue avec oignon râpé, cumin, paprika et coriandre ; forme des boudins.|Grille 8 min.|Sers avec le boulgour, la tomate et la sauce yaourt-menthe.",
    "Plus parfumé qu'un steak haché, pour la même quantité de protéines."),
  X('pl-filet-mignon-miel', "Filet mignon miel-soja, riz & brocoli", 'plat', 35, '',
    "Filet mignon de porc cuit@150; Miel@5; Sauce soja@10; Riz basmati cuit@150; Brocoli cuit@150",
    "Ail|Gingembre",
    "Badigeonne le filet mignon de miel, soja, ail et gingembre.|Enfourne 25 min à 190 °C.|Tranche et sers avec riz et brocoli.",
    "Le filet mignon est aussi maigre que le blanc de poulet."),
  X('pl-saumon-four', "Saumon au four, riz complet & brocoli", 'plat', 25, '',
    "Saumon cuit@130; Riz complet cuit@150; Brocoli cuit@150; Citron (jus)@10",
    "Aneth|Poivre",
    "Enfourne le saumon 12 min à 200 °C avec citron et aneth.|Cuis riz et brocoli.",
    "Simple, rapide, et plein d'oméga-3."),
  X('pl-saumon-lentilles', "Pavé de saumon, lentilles & épinards", 'plat', 25, '',
    "Saumon cuit@130; Lentilles cuites@150; Épinards frais@80; Citron (jus)@10",
    "Échalote|Moutarde",
    "Chauffe les lentilles avec l'échalote et une pointe de moutarde.|Fais tomber les épinards.|Poêle le saumon côté peau 6 min puis 2 min de l'autre côté.",
    "Lentilles + saumon : fer, fibres et protéines dans une assiette."),
  X('pl-cabillaud-parmesan', "Cabillaud en croûte de parmesan & purée de chou-fleur", 'plat', 30, '',
    "Cabillaud cuit@180; Parmesan@10; Pain de mie complet@15; Chou-fleur@250; Lait demi-écrémé@30",
    "Persil|Citron",
    "Mixe pain, parmesan et persil ; étale sur le poisson.|Enfourne 12 min à 200 °C.|Cuis le chou-fleur 12 min et mixe-le avec le lait.",
    "Le poisson blanc est l'une des protéines les moins caloriques."),
  X('pl-colin-tomate', "Colin à la tomate & olives, semoule", 'plat', 25, '',
    "Colin (lieu) cuit@180; Tomates concassées (boîte)@150; Olives noires@15; Semoule cuite@150",
    "Ail|Origan|Câpres",
    "Fais mijoter tomates, ail, olives et origan 10 min.|Dépose le poisson dessus, couvre et cuis 8 min.|Sers avec la semoule.",
    "Le colin coûte souvent moins cher que le cabillaud, pour les mêmes qualités."),
  X('pl-colin-ratatouille', "Colin, riz & ratatouille rapide", 'plat', 35, 'batch',
    "Colin (lieu) cuit@180; Riz basmati cuit@150; Courgette cuite@100; Aubergine@100; Poivron@60; Tomates concassées (boîte)@100",
    "Ail|Herbes de Provence|Huile d'olive",
    "Fais revenir les légumes en dés 15 min, ajoute les tomates et les herbes.|Cuis le poisson en papillote ou à la poêle.|Sers avec le riz.",
    "La ratatouille se garde 4 jours : fais-en une grande casserole."),
  X('pl-fish-chips', "Fish & chips au four", 'plat', 40, '',
    "Cabillaud cuit@180; Œuf entier@20; Pain de mie complet@25; Pomme de terre cuite@250; Huile d'olive@5; Petits pois@80",
    "Paprika|Citron",
    "Coupe les pommes de terre en frites, mélange avec l'huile et le paprika, 30 min à 220 °C.|Pane le poisson (œuf puis chapelure de pain) et ajoute-le au four les 15 dernières minutes.|Sers avec les petits pois et du citron.",
    "Bien moins gras qu'en friteuse, et le poisson reste moelleux."),
  X('pl-crevettes-courgettes', "Crevettes ail & persil, riz & courgettes", 'plat', 20, '',
    "Crevettes cuites@150; Riz basmati cuit@150; Courgette cuite@150; Huile d'olive@5",
    "Ail|Persil|Citron",
    "Fais sauter les courgettes en demi-lunes 6 min.|Ajoute les crevettes, l'ail et le persil 2 min.|Sers avec le riz et un filet de citron.",
    "Prêt en 20 minutes, très léger."),
  X('pl-tortilla-esp', "Tortilla espagnole légère", 'plat', 30, 'vege lunchbox',
    "Œuf entier@150; Pomme de terre cuite@150; Oignon jaune@40; Huile d'olive@5; Salade verte@60",
    "Sel, poivre",
    "Fais revenir l'oignon et les pommes de terre en fines tranches dans l'huile 10 min.|Verse les œufs battus, cuis à feu doux 8 min à couvert.|Retourne à l'aide d'une assiette, 2 min. Sers avec la salade.",
    "Se mange chaude ou froide : parfaite en lunchbox."),
  X('pl-galette-complete', "Galette de sarrasin complète", 'plat', 15, '',
    "Galette de sarrasin@120; Jambon blanc@60; Œuf entier@60; Emmental@20; Champignons de Paris@50",
    "Poivre",
    "Chauffe une galette dans une poêle, ajoute emmental, jambon et champignons poêlés.|Casse l'œuf au centre, couvre 3 min.|Replie les bords. Répète avec la deuxième galette ou partage la garniture.",
    "La farine de sarrasin est sans gluten et riche en fibres."),
  X('pl-pizza-tortilla', "Pizza tortilla jambon-champignons", 'plat', 15, '',
    "Tortilla complète (wrap)@60; Coulis de tomate@60; Mozzarella@50; Jambon blanc@50; Champignons de Paris@50; Salade verte@60",
    "Origan",
    "Étale le coulis sur la tortilla, ajoute champignons, jambon et mozzarella.|8 à 10 min au four à 220 °C, directement sur la grille.|Sers avec une salade.",
    "L'envie de pizza satisfaite pour environ 400 kcal."),
  X('pl-tofu-soja', "Tofu sauté soja-sésame & riz", 'plat', 20, 'vege',
    "Tofu nature@150; Riz basmati cuit@150; Poivron@80; Brocoli cuit@100; Sauce soja@15; Graines de sésame@5",
    "Ail|Gingembre|Maïzena",
    "Égoutte et presse le tofu, coupe en cubes, roule-les dans un peu de maïzena.|Dore-les à la poêle 8 min.|Ajoute légumes et sauce soja, parsème de sésame. Sers avec le riz.",
    "Presser le tofu 10 min sous un poids le rend bien plus croustillant."),
  X('pl-curry-lentilles', "Curry de lentilles corail & patate douce", 'plat', 30, 'vege batch',
    "Lentilles corail cuites@150; Patate douce cuite@150; Lait de coco léger@50; Épinards frais@60; Riz basmati cuit@100",
    "Curry|Gingembre|Ail|Oignon",
    "Fais revenir oignon, ail, gingembre et curry.|Ajoute 60 g de lentilles sèches, la patate douce en dés, le lait de coco et 300 ml d'eau ; 20 min.|Ajoute les épinards. Sers avec le riz.",
    "Doux, parfumé, et moins de 2 € la portion."),
  X('pl-poulet-legumes-soleil', "Poulet & légumes du soleil au four, quinoa", 'plat', 40, 'batch',
    "Blanc de poulet cuit@130; Courgette cuite@120; Aubergine@100; Tomates cerises@100; Quinoa cuit@120; Huile d'olive@5",
    "Herbes de Provence|Ail",
    "Mélange légumes et poulet en morceaux avec l'huile et les herbes.|30 min à 200 °C sur une plaque.|Sers avec le quinoa.",
    "Une plaque, un four, et le dîner se fait tout seul."),
  X('pl-gnocchi-poulet', "Poêlée de gnocchi, poulet & épinards", 'plat', 15, '',
    "Gnocchi@180; Blanc de poulet cuit@110; Épinards frais@80; Fromage frais allégé@20; Parmesan@5",
    "Ail",
    "Dore les gnocchi à sec 6 min.|Ajoute le poulet, l'ail et les épinards.|Termine avec le fromage frais et le parmesan.",
    "Rapide et réconfortant."),
  X('pl-blanquette', "Blanquette de dinde légère", 'plat', 40, 'batch',
    "Escalope de dinde cuite@150; Carottes@100; Champignons de Paris@80; Crème légère 15 %@20; Riz basmati cuit@150",
    "Bouillon cube|Citron|Laurier",
    "Cuis la dinde en cubes, les carottes et le laurier 25 min dans le bouillon.|Ajoute les champignons 5 min.|Hors du feu, lie avec la crème et un peu de citron. Sers avec le riz.",
    "Pas de roux au beurre : la crème légère suffit à lier."),
  X('pl-oeufs-cocotte', "Œufs cocotte épinards-jambon & pain complet", 'plat', 20, '',
    "Œuf entier@120; Épinards frais@80; Jambon blanc@40; Crème légère 15 %@15; Pain de mie complet@50",
    "Muscade|Ciboulette",
    "Répartis épinards tombés et jambon dans deux ramequins.|Casse un œuf dans chacun, ajoute une cuillère de crème.|12 min au four à 180 °C au bain-marie. Sers avec le pain grillé.",
    "Un dîner léger quand tu as peu faim."),
  X('pl-sardines-pdt', "Sardines, pommes de terre tièdes & salade", 'plat', 15, '',
    "Sardines à l'huile d'olive@100; Pomme de terre cuite@200; Salade verte@80; Oignon rouge@20",
    "Vinaigre|Moutarde|Persil",
    "Cuis les pommes de terre et coupe-les tièdes.|Assaisonne d'une vinaigrette moutarde sans huile (l'huile des sardines suffit).|Ajoute les sardines, l'oignon et la salade.",
    "Un plat de bistrot bon marché et riche en oméga-3."),

  /* ====================== GRATINS & HACHIS ====================== */
  X('gr-tartiflette', "Tartiflette allégée", 'gratin', 45, '',
    "Pomme de terre cuite@250; Reblochon@40; Allumettes de volaille@60; Oignon jaune@40; Fromage blanc 0 %@50; Salade verte@80",
    "Poivre|Ail",
    "Fais revenir l'oignon et les allumettes de volaille.|Mélange avec les pommes de terre en rondelles et le fromage blanc.|Dispose dans un plat, pose le reblochon en tranches dessus. 25 min à 200 °C. Sers avec la salade.",
    "40 g de reblochon au lieu de 100 : il gratine sur le dessus, et c'est là qu'il compte."),
  X('gr-dauphinois', "Gratin dauphinois léger & jambon", 'gratin', 60, 'batch',
    "Pomme de terre cuite@250; Lait demi-écrémé@100; Emmental@15; Jambon blanc@60; Salade verte@60",
    "Ail|Muscade",
    "Frotte le plat à l'ail. Dispose les pommes de terre crues en fines rondelles.|Verse le lait chaud muscadé, parsème d'emmental.|1 h à 170 °C. Sers avec le jambon et la salade.",
    "Le lait demi-écrémé remplace la crème : l'amidon des pommes de terre épaissit tout seul."),
  X('gr-brocoli', "Gratin de brocoli au poulet", 'gratin', 30, '',
    "Brocoli cuit@250; Blanc de poulet cuit@120; Lait demi-écrémé@60; Fromage frais allégé@20; Emmental@20; Pain de mie complet@40",
    "Muscade|Ail",
    "Cuis le brocoli 6 min.|Dans un plat : brocoli, poulet, sauce lait-fromage frais muscadée, emmental.|20 min à 200 °C. Sers avec le pain.",
    "Très volumineux pour peu de calories."),
  X('gr-poireaux', "Gratin de poireaux au jambon", 'gratin', 40, '',
    "Poireau@250; Jambon blanc@80; Lait demi-écrémé@80; Emmental@20; Farine T55@8; Pomme de terre cuite@120",
    "Muscade",
    "Cuis les poireaux coupés en tronçons 10 min, égoutte bien.|Béchamel légère : farine délayée à froid dans le lait, chauffe en fouettant.|Enroule les poireaux dans le jambon, nappe de sauce, emmental. 20 min à 200 °C.",
    "Une béchamel sans beurre, avec juste de la farine et du lait."),
  X('gr-endives', "Gratin d'endives au jambon allégé", 'gratin', 45, '',
    "Endive@250; Jambon blanc@80; Lait demi-écrémé@100; Farine T55@8; Beurre doux@3; Emmental@15; Pomme de terre cuite@120",
    "Muscade|Sucre (une pincée)",
    "Cuis les endives 15 min à la vapeur et presse-les pour enlever l'eau.|Béchamel légère avec le beurre, la farine et le lait.|Roule chaque endive dans une tranche de jambon, nappe, parsème d'emmental. 20 min à 200 °C.",
    "Bien presser les endives évite un gratin qui baigne dans l'eau."),
  X('gr-gnocchi', "Gratin de gnocchi tomate-mozzarella", 'gratin', 30, '',
    "Gnocchi@200; Coulis de tomate@150; Mozzarella@50; Blanc de dinde (tranches)@60; Épinards frais@50",
    "Basilic|Ail",
    "Mélange les gnocchi crus avec le coulis, l'ail, les épinards et la dinde en lanières.|Couvre de mozzarella.|20 min à 200 °C.",
    "Pas besoin de précuire les gnocchi : ils cuisent dans la sauce."),
  X('gr-hachis-poisson', "Hachis parmentier de poisson", 'gratin', 45, 'batch',
    "Cabillaud cuit@150; Pomme de terre cuite@200; Lait demi-écrémé@50; Épinards frais@60; Emmental@15",
    "Citron|Muscade",
    "Poche le poisson 8 min dans l'eau frémissante, émiette-le.|Fais une purée avec le lait.|Dans un plat : poisson, épinards, purée, emmental. 20 min à 200 °C.",
    "Une bonne façon de manger du poisson quand on n'aime pas trop ça."),
  X('gr-hachis-lentilles', "Hachis de lentilles & patate douce", 'gratin', 45, 'vege batch',
    "Lentilles cuites@150; Patate douce cuite@200; Carottes@60; Coulis de tomate@80; Emmental@15",
    "Oignon|Thym|Paprika",
    "Fais revenir oignon et carotte, ajoute les lentilles et le coulis 10 min.|Écrase la patate douce en purée.|Superpose, parsème d'emmental, 20 min à 200 °C.",
    "Version végétarienne qui rassasie autant que l'original."),
  X('gr-clafoutis-courgette', "Clafoutis de courgettes au thon", 'gratin', 45, 'lunchbox',
    "Courgette cuite@200; Thon au naturel@100; Œuf entier@100; Lait demi-écrémé@60; Emmental@15",
    "Herbes de Provence",
    "Fais revenir la courgette en dés 8 min.|Bats œufs et lait, ajoute thon, courgette et herbes.|Verse dans un plat, emmental dessus, 30 min à 180 °C.",
    "Se mange froid le lendemain."),
  X('gr-butternut', "Gratin de butternut, dinde & chèvre", 'gratin', 45, '',
    "Courge butternut@250; Escalope de dinde cuite@120; Bûche de chèvre@20; Lait demi-écrémé@50",
    "Muscade|Thym|Miel (facultatif)",
    "Coupe la courge en fines tranches, précuis 10 min à la vapeur.|Dans un plat : courge, dinde en lanières, lait muscadé, rondelles de chèvre.|25 min à 190 °C.",
    "Doux et parfumé, parfait en automne."),
  X('gr-parmentier-patate', "Parmentier de patate douce au poulet", 'gratin', 45, 'batch',
    "Patate douce cuite@250; Blanc de poulet cuit@130; Épinards frais@60; Emmental@15",
    "Paprika|Oignon",
    "Effiloche le poulet et mélange-le avec oignon, épinards et paprika.|Recouvre de purée de patate douce et d'emmental.|20 min à 200 °C.",
    "La patate douce apporte un goût légèrement sucré qui change du classique."),
  X('gr-aubergines', "Aubergines farcies bœuf-tomate", 'gratin', 50, '',
    "Aubergine@250; Steak haché 5 % (cuit)@120; Tomates concassées (boîte)@100; Mozzarella@30; Semoule cuite@100",
    "Ail|Cumin|Menthe",
    "Coupe l'aubergine en deux, quadrille la chair, 25 min à 200 °C.|Récupère la chair, mélange avec le bœuf revenu, la tomate et les épices.|Remplis les demi-aubergines, mozzarella dessus, 15 min. Sers avec la semoule.",
    "L'aubergine au four n'absorbe pas d'huile, contrairement à la poêle."),
  X('gr-tian', "Tian de légumes & poulet, semoule", 'gratin', 50, 'batch',
    "Courgette cuite@150; Tomate@120; Aubergine@100; Blanc de poulet cuit@120; Huile d'olive@5; Semoule cuite@120",
    "Herbes de Provence|Ail",
    "Coupe les légumes en rondelles et alterne-les dans un plat.|Arrose d'huile, d'ail et d'herbes. 40 min à 180 °C.|Sers avec le poulet grillé et la semoule.",
    "Un plat du soleil très léger."),
  X('gr-poivrons-farcis', "Poivrons farcis bœuf & riz", 'gratin', 50, 'batch',
    "Poivron@200; Steak haché 5 % (cuit)@110; Riz basmati cuit@100; Coulis de tomate@80; Emmental@10",
    "Oignon|Paprika|Ail",
    "Coupe le chapeau des poivrons et vide-les.|Mélange bœuf revenu, riz, coulis et épices ; remplis les poivrons.|Emmental dessus, 35 min à 190 °C.",
    "Chaque poivron est une portion : facile pour les gamelles."),

  /* ====================== SOUPES ====================== */
  X('so-lentilles-corail', "Soupe de lentilles corail, carotte & cumin", 'soupe', 30, 'vege batch',
    "Lentilles corail cuites@180; Carottes@150; Lait de coco léger@30; Pain de mie complet@40; Oignon jaune@30",
    "Cumin|Citron|Bouillon cube",
    "Fais revenir l'oignon et le cumin.|Ajoute 70 g de lentilles sèches, les carottes en rondelles et 500 ml de bouillon ; 20 min.|Mixe avec le lait de coco et un filet de citron. Sers avec le pain grillé.",
    "Une soupe qui cale vraiment grâce aux lentilles."),
  X('so-minestrone', "Minestrone protéiné", 'soupe', 35, 'batch',
    "Haricots blancs@100; Pâtes cuites@60; Courgette cuite@100; Carottes@80; Tomates concassées (boîte)@150; Parmesan@10",
    "Ail|Basilic|Bouillon cube",
    "Fais revenir ail et légumes en dés.|Ajoute tomates, 500 ml de bouillon, puis les pâtes sèches (25 g) et les haricots ; 15 min.|Sers avec le parmesan et du basilic.",
    "Une soupe-repas complète."),
  X('so-butternut', "Velouté de butternut & poulet", 'soupe', 35, 'batch',
    "Courge butternut@300; Blanc de poulet cuit@100; Crème légère 15 %@15; Pain de mie complet@40; Oignon jaune@30",
    "Muscade|Bouillon cube",
    "Cuis la courge et l'oignon dans le bouillon 20 min.|Mixe avec la crème.|Ajoute le poulet effiloché dans le bol. Sers avec le pain.",
    "Le poulet dans la soupe la transforme en vrai repas."),
  X('so-brocoli-chevre', "Velouté de brocoli, chèvre frais & jambon", 'soupe', 25, '',
    "Brocoli cuit@250; Pomme de terre cuite@100; Fromage de chèvre frais@30; Jambon blanc@60",
    "Bouillon cube|Poivre",
    "Cuis brocoli et pomme de terre dans le bouillon 15 min.|Mixe avec le chèvre frais.|Sers avec le jambon à côté ou en lanières dans le bol.",
    "Le chèvre frais donne de l'onctuosité sans crème."),
  X('so-bouillon-asiat', "Bouillon asiatique nouilles, poulet & gingembre", 'soupe', 20, '',
    "Nouilles de riz cuites@150; Blanc de poulet cuit@110; Champignons de Paris@60; Épinards frais@40; Gingembre frais@5; Sauce soja@10",
    "Bouillon de volaille|Citron vert|Coriandre|Piment",
    "Fais frémir 500 ml de bouillon avec le gingembre et la sauce soja.|Ajoute champignons et nouilles 3 min, puis poulet et épinards.|Citron vert, coriandre et piment au moment de servir.",
    "Réconfortant et très peu gras."),
  X('so-pois-chiches', "Soupe de pois chiches, tomate & épinards", 'soupe', 25, 'vege',
    "Pois chiches cuits@150; Tomates concassées (boîte)@200; Épinards frais@50; Yaourt nature 0 %@30; Oignon jaune@30",
    "Harissa|Cumin|Ail",
    "Fais revenir oignon, ail, cumin et une pointe de harissa.|Ajoute tomates, pois chiches et 250 ml d'eau ; 15 min.|Ajoute les épinards. Sers avec une cuillère de yaourt.",
    "Épicée et rassasiante."),
  X('so-courgette-oeuf', "Velouté de courgettes, fromage frais & œuf mollet", 'soupe', 25, 'vege',
    "Courgette cuite@300; Pomme de terre cuite@80; Fromage frais allégé@30; Œuf entier@60; Pain de mie complet@40",
    "Bouillon cube|Basilic",
    "Cuis courgettes et pomme de terre dans le bouillon 15 min.|Mixe avec le fromage frais.|Cuis l'œuf 6 min, écale-le et pose-le dans la soupe. Pain grillé à côté.",
    "L'œuf mollet transforme un velouté léger en vrai dîner."),
  X('so-choufleur-crevettes', "Soupe de chou-fleur au curry & crevettes", 'soupe', 25, '',
    "Chou-fleur@300; Crevettes cuites@100; Lait de coco léger@40; Pain de mie complet@30",
    "Curry|Bouillon cube",
    "Cuis le chou-fleur dans le bouillon avec le curry 15 min.|Mixe avec le lait de coco.|Ajoute les crevettes dans le bol.",
    "Moins de 300 kcal pour un grand bol."),
  X('so-gaspacho', "Gaspacho & tartines au thon", 'soupe', 15, 'froid',
    "Tomate@250; Concombre@100; Poivron@60; Huile d'olive@5; Pain de mie complet@40; Thon au naturel@80",
    "Ail|Vinaigre de xérès|Sel",
    "Mixe tomates, concombre, poivron, ail, huile et un filet de vinaigre. Mets au frais.|Tartine le pain grillé de thon émietté, poivre.",
    "Rafraîchissant l'été, plein de légumes sans cuisson."),

  /* ====================== SALADES ====================== */
  X('sa-cesar', "Salade César légère", 'salade', 15, '',
    "Salade verte@100; Blanc de poulet cuit@130; Pain de mie complet@30; Parmesan@10; Yaourt nature 0 %@40; Moutarde@5; Citron (jus)@10",
    "Ail|Poivre",
    "Sauce : yaourt, moutarde, citron, ail râpé et poivre.|Fais griller le pain en cubes à sec (croûtons).|Mélange salade, poulet, sauce, croûtons et copeaux de parmesan.",
    "La sauce au yaourt divise par 4 les calories de la sauce César."),
  X('sa-endives', "Salade endives, pomme, noix & jambon", 'salade', 10, 'froid',
    "Endive@200; Pomme@80; Cerneaux de noix@10; Jambon blanc@80; Fromage blanc 0 %@30; Moutarde@5; Pain de mie complet@40",
    "Vinaigre|Ciboulette",
    "Émince endives et pomme.|Sauce : fromage blanc, moutarde, vinaigre et ciboulette.|Mélange avec le jambon en lanières et les noix. Pain à côté.",
    "Croquant, sucré-salé, prêt en 10 minutes."),
  X('sa-quinoa-mangue', "Salade quinoa, crevettes & mangue", 'salade', 15, 'lunchbox',
    "Quinoa cuit@120; Crevettes cuites@120; Mangue@60; Avocat@30; Concombre@60",
    "Citron vert|Coriandre|Piment",
    "Cuis 45 g de quinoa sec et laisse refroidir.|Coupe mangue, avocat et concombre en dés.|Mélange avec les crevettes et assaisonne de citron vert.",
    "Parfaite en lunchbox d'été."),
  X('sa-haricots-thon', "Salade haricots blancs, thon & tomates", 'salade', 10, 'froid lunchbox',
    "Haricots blancs@150; Thon au naturel@100; Tomates cerises@100; Oignon rouge@20; Huile d'olive@5",
    "Vinaigre|Persil",
    "Rince les haricots.|Mélange avec le thon, les tomates coupées, l'oignon émincé, l'huile, le vinaigre et le persil.",
    "100 % placard et prête en 10 minutes."),
  X('sa-lentilles-saumon', "Salade lentilles, saumon fumé & radis", 'salade', 10, 'froid',
    "Lentilles cuites@150; Saumon fumé@50; Radis@60; Yaourt nature 0 %@30; Salade verte@30",
    "Aneth|Moutarde|Citron",
    "Assaisonne les lentilles d'une sauce yaourt-moutarde-citron.|Ajoute radis en rondelles, salade et saumon en lanières.",
    "Des fibres, des protéines et des oméga-3 sans cuisson."),
  X('sa-patate-feta', "Salade tiède patate douce, feta & pois chiches", 'salade', 30, 'vege',
    "Patate douce cuite@150; Pois chiches cuits@100; Feta@30; Épinards frais@50; Huile d'olive@5",
    "Cumin|Citron|Miel (facultatif)",
    "Rôtis la patate douce et les pois chiches 25 min à 200 °C avec le cumin.|Mélange tiède avec les épinards, la feta, l'huile et le citron.",
    "Le tiède fait légèrement fondre la feta : délicieux."),
  X('sa-riz-poulet', "Salade de riz complet, poulet & poivrons", 'salade', 15, 'lunchbox',
    "Riz complet cuit@150; Blanc de poulet cuit@120; Poivron@80; Maïs doux (boîte)@40; Yaourt nature 0 %@30",
    "Moutarde|Paprika|Citron",
    "Mélange riz froid, poulet en dés, poivron et maïs.|Assaisonne d'une sauce yaourt-moutarde-citron.",
    "Le riz complet cale plus longtemps que le blanc."),
  X('sa-pates-grecque', "Salade de pâtes à la grecque & poulet", 'salade', 15, 'lunchbox',
    "Pâtes cuites@150; Feta@30; Concombre@80; Tomates cerises@80; Olives noires@15; Blanc de poulet cuit@100",
    "Origan|Citron|Oignon rouge",
    "Cuis 60 g de pâtes sèches, rince-les à l'eau froide.|Mélange avec tous les ingrédients, l'origan et le citron.",
    "Se garde 2 jours au frais."),
  X('sa-asiat-chou', "Salade asiatique chou, poulet & cajou", 'salade', 15, 'lunchbox',
    "Chou rouge@100; Carottes@80; Blanc de poulet cuit@120; Noix de cajou@10; Sauce soja@10; Nouilles de riz cuites@100; Edamame surgelés@40",
    "Vinaigre de riz|Gingembre|Citron vert|Coriandre",
    "Émince le chou, râpe les carottes.|Sauce : soja, vinaigre de riz, gingembre et citron vert.|Mélange avec nouilles, poulet, edamame et noix de cajou concassées.",
    "Très croquante, elle ne ramollit pas en lunchbox."),
  X('sa-caprese', "Salade caprese protéinée", 'salade', 10, 'froid',
    "Tomate@200; Mozzarella@60; Blanc de dinde (tranches)@60; Pain de mie complet@40; Pesto@8",
    "Basilic|Vinaigre balsamique",
    "Tranche tomates et mozzarella, alterne-les avec la dinde.|Détends le pesto avec un peu d'eau et arrose. Pain grillé à côté.",
    "La dinde ajoute 12 g de protéines sans alourdir."),
  X('sa-mexicaine', "Salade mexicaine au poulet", 'salade', 15, 'lunchbox',
    "Haricots rouges cuits@120; Maïs doux (boîte)@60; Poivron@80; Blanc de poulet cuit@100; Avocat@30; Tomate@80",
    "Cumin|Citron vert|Coriandre|Piment",
    "Rince haricots et maïs.|Coupe poivron, tomate et avocat en dés.|Mélange avec le poulet, le citron vert et les épices.",
    "Riche en fibres : elle rassasie jusqu'au soir."),
  X('sa-semoule-orange', "Salade de semoule à l'orange & poulet", 'salade', 15, 'lunchbox',
    "Semoule cuite@150; Orange@100; Blanc de poulet cuit@120; Carottes@60",
    "Cumin|Menthe|Cannelle (une pincée)",
    "Prépare 55 g de semoule sèche.|Ajoute l'orange en dés avec son jus, la carotte râpée, le poulet et la menthe.",
    "L'orange remplace l'huile pour humidifier la semoule."),
  X('sa-cobb', "Salade Cobb allégée", 'salade', 20, '',
    "Salade verte@80; Blanc de poulet cuit@100; Œuf entier@60; Tomates cerises@80; Avocat@30; Filet de bacon@30; Yaourt nature 0 %@30",
    "Moutarde|Ciboulette",
    "Cuis l'œuf 9 min, dore le bacon.|Dispose en rangées : salade, poulet, œuf, tomates, avocat, bacon.|Sauce yaourt-moutarde-ciboulette.",
    "Une salade-repas américaine en version raisonnable."),
  X('sa-sardines', "Salade sardines, pommes de terre & haricots verts", 'salade', 20, '',
    "Sardines à l'huile d'olive@100; Pomme de terre cuite@180; Haricots verts@120; Tomates cerises@60; Moutarde@5",
    "Vinaigre|Échalote",
    "Cuis pommes de terre et haricots verts.|Vinaigrette : moutarde, vinaigre, échalote (sans huile).|Mélange tiède avec les tomates et les sardines.",
    "Façon niçoise, en plus économique."),
  X('sa-boulgour-tofu', "Salade de boulgour aux herbes & tofu fumé", 'salade', 15, 'vege lunchbox',
    "Boulgour cuit@150; Tofu fumé@100; Concombre@80; Tomates cerises@80; Citron (jus)@15; Huile d'olive@5",
    "Persil|Menthe",
    "Prépare 55 g de boulgour.|Ajoute tofu en dés, concombre, tomates, herbes, citron et huile.",
    "Un taboulé libanais version protéinée."),
  X('sa-cottage-radis', "Salade croquante concombre, radis, cottage & œuf", 'salade', 15, 'froid',
    "Concombre@150; Radis@60; Cottage cheese@150; Œuf entier@60; Pain de mie complet@40",
    "Ciboulette|Poivre",
    "Cuis l'œuf 9 min.|Coupe concombre et radis en rondelles.|Mélange avec le cottage et la ciboulette, ajoute l'œuf en quartiers. Pain à côté.",
    "Frais, léger, et près de 30 g de protéines."),

  /* ====================== WRAPS & SANDWICHS ====================== */
  X('wr-burger', "Burger maison allégé", 'wrap', 20, '',
    "Pain burger complet@75; Steak haché 5 % (cuit)@125; Cheddar@20; Tomate@50; Salade verte@20; Oignon rouge@20; Ketchup@15",
    "Cornichons|Moutarde",
    "Cuis le steak 2 à 3 min par face, pose le cheddar dessus en fin de cuisson.|Toaste le pain.|Monte le burger : ketchup, salade, steak, tomate, oignon.",
    "Viande à 5 %, pain complet, sauce dosée : près de 45 g de protéines, bien plus qu'un burger de fast-food."),
  X('wr-burger-poulet', "Burger de poulet croustillant", 'wrap', 25, '',
    "Pain burger complet@75; Blanc de poulet cuit@120; Œuf entier@20; Pain de mie complet@15; Salade verte@20; Tomate@40; Mayonnaise allégée@10",
    "Paprika",
    "Aplatis le filet, passe-le dans l'œuf puis dans le pain mixé avec du paprika.|Cuis 15 min au four à 210 °C.|Monte le burger avec la sauce, la salade et la tomate.",
    "Croustillant au four, sans friture."),
  X('wr-bagel-saumon', "Bagel saumon fumé & fromage frais", 'wrap', 5, 'froid',
    "Bagel@85; Saumon fumé@50; Fromage frais allégé@30; Concombre@40",
    "Aneth|Citron",
    "Toaste le bagel.|Tartine de fromage frais, ajoute concombre, saumon, aneth et citron.",
    "Un classique de brunch prêt en 5 minutes."),
  X('wr-club', "Club sandwich poulet allégé", 'wrap', 15, 'lunchbox',
    "Pain de mie complet@75; Blanc de poulet cuit@100; Filet de bacon@20; Tomate@50; Salade verte@20; Mayonnaise allégée@10",
    "Moutarde",
    "Toaste 3 tranches de pain, dore le bacon.|Monte en étages : sauce, salade, poulet, tomate, bacon.|Coupe en triangles.",
    "Le filet de bacon remplace le bacon classique : bien moins gras."),
  X('wr-croque', "Croque-monsieur allégé & salade", 'wrap', 15, '',
    "Pain de mie complet@80; Jambon blanc@60; Emmental@20; Fromage blanc 0 %@20; Salade verte@80",
    "Moutarde|Muscade",
    "Tartine le pain de fromage blanc et d'un peu de moutarde.|Ajoute jambon et emmental, referme.|Au four 10 min à 200 °C ou à l'appareil. Sers avec la salade.",
    "Le fromage blanc remplace la béchamel et le beurre."),
  X('wr-cheeseburger', "Wrap façon cheeseburger", 'wrap', 15, 'lunchbox',
    "Tortilla de blé (wrap)@60; Steak haché 5 % (cuit)@110; Cheddar@20; Salade verte@20; Tomate@40; Ketchup@10; Oignon rouge@15",
    "Cornichons|Moutarde",
    "Poêle le steak émietté.|Garnis la tortilla : ketchup, moutarde, salade, viande, cheddar, tomate, oignon, cornichons.|Roule et toaste 1 min par face.",
    "Tout le goût d'un cheeseburger, facile à emporter."),
  X('wr-tofu', "Wrap tofu fumé, houmous & crudités", 'wrap', 10, 'vege froid',
    "Tortilla complète (wrap)@60; Tofu fumé@80; Houmous@30; Carottes@40; Salade verte@20; Concombre@40",
    "Paprika",
    "Tranche finement le tofu fumé.|Tartine la tortilla de houmous, ajoute les crudités et le tofu.|Roule serré.",
    "Aucune cuisson nécessaire."),
  X('wr-crevettes-mangue', "Wrap crevettes, mangue & avocat", 'wrap', 10, 'froid',
    "Tortilla de blé (wrap)@60; Crevettes cuites@100; Mangue@50; Avocat@30; Salade verte@20; Yaourt nature 0 %@20",
    "Citron vert|Piment",
    "Mélange le yaourt avec le citron vert et un peu de piment.|Garnis la tortilla de salade, crevettes, mangue et avocat.|Roule.",
    "Frais et exotique."),
  X('wr-thon-cottage', "Wrap thon, cottage & concombre", 'wrap', 5, 'froid lunchbox',
    "Tortilla complète (wrap)@60; Thon au naturel@100; Cottage cheese@60; Concombre@60; Salade verte@20",
    "Ciboulette|Citron",
    "Mélange le thon avec le cottage, la ciboulette et le citron.|Garnis la tortilla avec la salade et le concombre, roule.",
    "Plus de 40 g de protéines pour environ 380 kcal."),
  X('wr-quesadilla', "Quesadilla poulet, haricots & fromage", 'wrap', 15, '',
    "Tortilla de blé (wrap)@120; Blanc de poulet cuit@80; Haricots rouges cuits@60; Emmental@20; Poivron@50",
    "Cumin|Paprika",
    "Écrase grossièrement les haricots avec le cumin.|Sur une tortilla : haricots, poulet, poivron, emmental. Couvre de la deuxième.|Dore 3 min par face à la poêle sèche, coupe en parts.",
    "La poêle sèche suffit : aucune huile nécessaire."),
  X('wr-pita-kefta', "Pita bœuf, yaourt & crudités", 'wrap', 15, '',
    "Pain pita@70; Steak haché 5 % (cuit)@110; Yaourt nature 0 %@40; Tomate@50; Concombre@50; Oignon rouge@15",
    "Cumin|Menthe|Ail",
    "Poêle la viande avec le cumin.|Sauce yaourt, ail et menthe.|Garnis la pita chaude de viande, crudités et sauce.",
    "Le kebab maison, sans friture et sans sauce blanche grasse."),
  X('wr-galette-saumon', "Galette de sarrasin saumon fumé & fromage frais", 'wrap', 10, '',
    "Galette de sarrasin@120; Saumon fumé@60; Fromage frais allégé@30; Épinards frais@40",
    "Citron|Aneth",
    "Chauffe la galette à la poêle.|Tartine les 2 galettes de fromage frais, ajoute les épinards et le saumon.|Plie en quatre, citron et aneth.",
    "Léger et chic, prêt en 10 minutes."),
  X('wr-thon-oeuf', "Sandwich complet thon-œuf", 'wrap', 15, 'lunchbox',
    "Pain de mie complet@80; Thon au naturel@80; Œuf entier@60; Yaourt nature 0 %@20; Salade verte@20",
    "Moutarde|Ciboulette",
    "Cuis l'œuf 9 min, écrase-le avec le thon, le yaourt et la moutarde.|Garnis le pain avec la salade.",
    "Le yaourt remplace la mayonnaise : environ 100 kcal de moins."),
  X('wr-pesto-mozza', "Wrap poulet, pesto & mozzarella", 'wrap', 10, 'lunchbox',
    "Tortilla de blé (wrap)@60; Blanc de poulet cuit@110; Pesto@10; Mozzarella@30; Tomate@50; Salade verte@20",
    "Basilic",
    "Tartine la tortilla de pesto.|Ajoute salade, poulet, tomate et mozzarella, roule.|Toaste 1 min par face si tu le veux chaud.",
    "Une bonne façon de finir un reste de poulet."),
  X('wr-dinde-cheddar', "Wrap dinde, cheddar & crudités", 'wrap', 5, 'froid lunchbox',
    "Tortilla complète (wrap)@60; Blanc de dinde (tranches)@80; Cheddar@20; Carottes@40; Salade verte@20; Moutarde@5",
    "Poivre",
    "Tartine la tortilla de moutarde.|Ajoute dinde, cheddar, carottes râpées et salade. Roule.",
    "5 minutes chrono pour une gamelle."),
  X('wr-laitue-teriyaki', "Wraps de laitue au poulet teriyaki", 'wrap', 20, '',
    "Salade verte@80; Blanc de poulet cuit@130; Carottes@50; Sauce soja@10; Miel@5; Riz basmati cuit@80",
    "Gingembre|Sésame",
    "Laque le poulet émincé avec la sauce soja, le miel et le gingembre.|Sers dans de grandes feuilles de laitue avec la carotte râpée et un peu de riz.",
    "Moins de glucides qu'un wrap classique, pour un dîner léger."),

  /* ====================== PETIT-DÉJ ====================== */
  X('pd-porridge-cacao', "Porridge protéiné cacao-banane", 'petitdej', 10, '',
    "Flocons d'avoine@50; Lait demi-écrémé@200; Whey protéine@20; Cacao non sucré@5; Banane@60",
    "Cannelle",
    "Cuis les flocons dans le lait 4 min en remuant.|Hors du feu, ajoute whey et cacao.|Garnis de rondelles de banane.",
    "La whey s'ajoute hors du feu pour éviter les grumeaux."),
  X('pd-porridge-pomme', "Porridge pomme-cannelle & skyr", 'petitdej', 10, '',
    "Flocons d'avoine@50; Lait demi-écrémé@200; Pomme@100; Skyr nature@100",
    "Cannelle",
    "Cuis les flocons dans le lait avec la pomme râpée et la cannelle.|Sers avec le skyr par-dessus.",
    "Goût de tarte aux pommes, sans sucre ajouté."),
  X('pd-omelette-blancs', "Omelette aux blancs, jambon & fromage", 'petitdej', 10, '',
    "Œuf entier@60; Blanc d'œuf@100; Jambon blanc@40; Emmental@15; Pain de mie complet@50",
    "Ciboulette|Poivre",
    "Bats l'œuf et les blancs.|Cuis à la poêle, ajoute jambon et emmental, plie en deux.|Sers avec le pain grillé.",
    "Environ 35 g de protéines pour 360 kcal."),
  X('pd-chia', "Pudding de chia au skyr & fruits rouges", 'petitdej', 5, 'froid',
    "Graines de chia@15; Skyr nature@150; Lait demi-écrémé@80; Fruits rouges surgelés@80",
    "Vanille|Miel (facultatif)",
    "La veille, mélange chia, skyr, lait et vanille dans un bocal.|Le matin, ajoute les fruits rouges.",
    "Le chia gonfle la nuit et donne une texture de crème dessert."),
  X('pd-tartines-saumon', "Tartines fromage frais & saumon fumé", 'petitdej', 5, 'froid',
    "Pain de mie complet@60; Fromage frais allégé@30; Saumon fumé@40",
    "Aneth|Citron",
    "Toaste le pain.|Tartine de fromage frais, ajoute le saumon, l'aneth et un filet de citron.",
    "Un petit-déj salé qui cale jusqu'à midi."),
  X('pd-pancakes-skyr', "Pancakes protéinés au skyr", 'petitdej', 15, '',
    "Flocons d'avoine@40; Œuf entier@60; Blanc d'œuf@60; Skyr nature@60; Fruits rouges surgelés@80",
    "Levure chimique|Vanille",
    "Mixe flocons, œuf, blancs, skyr, vanille et une pincée de levure.|Cuis de petits pancakes 2 min par face dans une poêle antiadhésive.|Sers avec les fruits rouges chauffés.",
    "Plus de 25 g de protéines dans une pile de pancakes."),
  X('pd-fb-kiwi', "Bol fromage blanc, kiwi & muesli", 'petitdej', 5, 'froid',
    "Fromage blanc 0 %@200; Kiwi@150; Muesli@30",
    "",
    "Verse le fromage blanc dans un bol.|Ajoute les kiwis en dés et le muesli.",
    "Deux kiwis couvrent tes besoins en vitamine C de la journée."),
  X('pd-oeufs-brouilles', "Œufs brouillés, pain complet & tomates cerises", 'petitdej', 10, '',
    "Œuf entier@120; Pain de mie complet@60; Tomates cerises@80",
    "Ciboulette|Poivre",
    "Brouille les œufs à feu doux en remuant sans arrêt.|Sers sur le pain grillé avec les tomates cerises.",
    "Cuits à feu doux, les œufs restent crémeux sans beurre."),
  X('pd-galette-oeuf', "Galette de sarrasin œuf-jambon (brunch)", 'petitdej', 10, '',
    "Galette de sarrasin@60; Œuf entier@60; Jambon blanc@40; Emmental@15",
    "Poivre",
    "Chauffe la galette, ajoute l'emmental et le jambon.|Casse l'œuf au centre, couvre 3 min.|Replie les bords.",
    "Le brunch du week-end en version raisonnable."),
  X('pd-bagel-oeuf', "Bagel œuf, dinde & avocat", 'petitdej', 10, '',
    "Bagel@85; Œuf entier@60; Blanc de dinde (tranches)@40; Avocat@30",
    "Poivre|Piment d'Espelette",
    "Toaste le bagel.|Cuis l'œuf au plat.|Garnis d'avocat écrasé, de dinde et de l'œuf.",
    "Un petit-déj costaud avant une séance."),
  X('pd-french-toast', "Pain perdu protéiné & fruits rouges", 'petitdej', 15, '',
    "Pain de mie complet@75; Œuf entier@60; Lait demi-écrémé@50; Skyr nature@100; Fruits rouges surgelés@80",
    "Cannelle|Vanille",
    "Bats l'œuf, le lait, la cannelle et la vanille.|Trempe le pain et dore-le à la poêle antiadhésive.|Sers avec le skyr et les fruits rouges.",
    "Le skyr remplace le sucre et la chantilly."),
  X('pd-smoothie-bowl', "Smoothie bowl mangue & skyr", 'petitdej', 5, 'froid',
    "Skyr nature@150; Mangue@100; Banane@50; Muesli@20",
    "",
    "Mixe skyr, mangue et banane (congelée, c'est encore mieux).|Verse dans un bol et parsème de muesli.",
    "Épais comme une glace grâce à la banane congelée."),
  X('pd-oats-cacahuete', "Overnight oats cacao & beurre de cacahuète", 'petitdej', 5, 'froid',
    "Flocons d'avoine@50; Lait demi-écrémé@150; Skyr nature@100; Cacao non sucré@5; Beurre de cacahuète@10",
    "",
    "La veille, mélange tout dans un bocal.|Le matin, c'est prêt : mange froid ou tiédi.",
    "Prépare 3 bocaux d'un coup pour les matins pressés."),
  X('pd-egg-muffins', "Muffins aux œufs épinards & feta", 'petitdej', 25, 'batch',
    "Œuf entier@120; Blanc d'œuf@60; Épinards frais@40; Feta@20; Poivron@40",
    "Poivre|Origan",
    "Bats œufs et blancs, ajoute épinards hachés, poivron en dés et feta.|Verse dans des moules à muffins.|20 min à 180 °C.",
    "Se gardent 4 jours au frais : 30 secondes au micro-ondes le matin."),
  X('pd-toast-cacahuete', "Toast beurre de cacahuète, banane & skyr", 'petitdej', 5, '',
    "Pain de mie complet@60; Beurre de cacahuète@15; Banane@60; Skyr nature@150",
    "Cannelle",
    "Toaste le pain, tartine de beurre de cacahuète, ajoute la banane.|Skyr à côté.",
    "Parfait avant une séance de renfo le matin."),
  X('pd-cottage-avocat', "Tartines cottage cheese, avocat & tomate", 'petitdej', 5, 'froid',
    "Pain de mie complet@60; Cottage cheese@100; Avocat@40; Tomate@60",
    "Piment d'Espelette|Poivre",
    "Toaste le pain.|Écrase l'avocat dessus, ajoute cottage et tomate en tranches.",
    "Version protéinée de l'avocado toast."),

  /* ====================== COLLATIONS ====================== */
  X('co-skyr-miel', "Skyr, miel & noix", 'collation', 2, 'froid',
    "Skyr nature@150; Miel@8; Cerneaux de noix@10",
    "", "Verse le skyr, ajoute le miel et les noix concassées.",
    "Une collation sucrée et protéinée."),
  X('co-pomme-cacahuete', "Pomme & beurre de cacahuète", 'collation', 2, 'froid vege',
    "Pomme@150; Beurre de cacahuète@15",
    "", "Coupe la pomme en quartiers et trempe-les dans le beurre de cacahuète.",
    "Mesure la cuillère : le beurre de cacahuète est très calorique."),
  X('co-petits-suisses', "Petits-suisses 0 % & fraises", 'collation', 2, 'froid',
    "Petit-suisse 0 %@120; Fraises@120",
    "Vanille", "Démoule les petits-suisses, ajoute les fraises coupées.",
    "Moins de 110 kcal pour 12 g de protéines."),
  X('co-mug-cake', "Mug cake protéiné au chocolat", 'collation', 5, '',
    "Whey protéine@25; Œuf entier@60; Flocons d'avoine@20; Cacao non sucré@5; Lait demi-écrémé@30",
    "Levure chimique",
    "Mélange tout dans un grand mug.|Micro-ondes 60 à 90 secondes.",
    "Pour les envies de gâteau du soir."),
  X('co-energy-balls', "Energy balls avoine & cacahuète", 'collation', 15, 'batch',
    "Flocons d'avoine@30; Beurre de cacahuète@15; Miel@5; Chocolat noir 70 %@5; Whey protéine@10",
    "",
    "Mélange tout avec une cuillère d'eau jusqu'à obtenir une pâte.|Forme 3 boules et mets au frais 30 min.",
    "Multiplie par 5 et garde-les une semaine au frais."),
  X('co-oeufs-crudites', "Œufs durs & crudités", 'collation', 12, 'froid',
    "Œuf entier@120; Carottes@80; Concombre@80; Houmous@20",
    "Sel, poivre",
    "Cuis les œufs 9 min, refroidis-les.|Coupe les crudités en bâtonnets, sers avec le houmous.",
    "Une collation salée qui coupe la faim."),
  X('co-galettes-dinde', "Galettes de riz, fromage frais & dinde", 'collation', 3, 'froid',
    "Galettes de riz@20; Fromage frais allégé@20; Blanc de dinde (tranches)@40",
    "Ciboulette", "Tartine les galettes de fromage frais et ajoute la dinde.",
    "Croquant et léger."),
  X('co-edamame', "Edamame au sel & citron", 'collation', 5, 'vege',
    "Edamame surgelés@120",
    "Fleur de sel|Citron", "Cuis les edamame 4 min dans l'eau bouillante.|Égoutte, sel et citron.",
    "Une des rares collations végétales riches en protéines."),
  X('co-fb-compote', "Fromage blanc, compote & amandes", 'collation', 2, 'froid',
    "Fromage blanc 0 %@150; Compote sans sucres ajoutés@100; Amandes@10",
    "Cannelle", "Mélange le fromage blanc et la compote, parsème d'amandes.",
    "Goût dessert, profil protéiné."),
  X('co-pois-chiches', "Pois chiches rôtis croustillants", 'collation', 30, 'vege batch',
    "Pois chiches cuits@120; Huile d'olive@3",
    "Paprika fumé|Cumin|Sel",
    "Rince et sèche bien les pois chiches.|Mélange avec l'huile et les épices, 30 min à 200 °C.",
    "Remplace les chips à l'apéro."),
  X('co-shake-choco', "Shake chocolat-cacahuète", 'collation', 3, '',
    "Lait demi-écrémé@250; Whey protéine@30; Cacao non sucré@5; Beurre de cacahuète@10",
    "Glaçons", "Mixe tout avec quelques glaçons.",
    "Idéal après une séance si le prochain repas est loin."),
  X('co-roules-jambon', "Roulés de jambon, fromage frais & concombre", 'collation', 5, 'froid',
    "Jambon blanc@60; Fromage frais allégé@20; Concombre@60",
    "Ciboulette", "Tartine les tranches de jambon de fromage frais, ajoute un bâtonnet de concombre et roule.",
    "Moins de 150 kcal pour 15 g de protéines."),
  X('co-grec-fraises', "Yaourt grec, fraises & chocolat noir", 'collation', 3, 'froid',
    "Yaourt grec@100; Fraises@120; Chocolat noir 70 %@10",
    "", "Mets le yaourt dans un bol, ajoute les fraises et le chocolat râpé.",
    "Un vrai dessert gourmand pour environ 200 kcal."),
  X('co-cottage-kiwi', "Cottage cheese & kiwi", 'collation', 2, 'froid',
    "Cottage cheese@150; Kiwi@75",
    "", "Mets le cottage dans un bol et ajoute le kiwi en dés.",
    "Pratique à emporter.")
);
