'use strict';
/* Cap 100 — base de recettes et d'ingrédients.
   Valeurs nutritionnelles moyennes indicatives pour 100 g. Les recettes sont données pour 1 portion. */

/* Rayons du magasin, dans l'ordre d'un parcours classique */
D.AISLES = [
  { id: 'fl', label: 'Fruits & légumes', icon: 'food' },
  { id: 'bo', label: 'Boulangerie', icon: 'sun' },
  { id: 'vi', label: 'Viandes & poissons', icon: 'flame' },
  { id: 'cr', label: 'Crémerie & œufs', icon: 'droplet' },
  { id: 'fe', label: 'Pâtes, riz & céréales', icon: 'grid' },
  { id: 'co', label: 'Conserves & bocaux', icon: 'pot' },
  { id: 'ep', label: 'Épicerie & sauces', icon: 'star' },
  { id: 'su', label: 'Surgelés', icon: 'sparkle' },
  { id: 'pl', label: 'Placard (à vérifier)', icon: 'list' },
  { id: 'au', label: 'Autres', icon: 'more' }
];

/* Ingrédients supplémentaires, ajoutés à la base d'aliments */
D.EXTRA_FOODS = [
  ['tortilla', 'Tortilla de blé (wrap)', 310, 8.5, 51, 7.5, 60, '1 tortilla', 'bo', { unitG: 60, unit: 'tortilla', units: 'tortillas' }],
  ['tortilla-c', 'Tortilla complète (wrap)', 290, 9.5, 46, 6.5, 60, '1 tortilla', 'bo', { unitG: 60, unit: 'tortilla', units: 'tortillas' }],
  ['pois-chiches', 'Pois chiches cuits', 140, 7.5, 18, 2.6, 130, '1/2 boîte', 'co', { unitG: 265, unit: 'boîte (400 g)', units: 'boîtes (400 g)' }],
  ['haricots-rouges', 'Haricots rouges cuits', 115, 8.5, 15, 0.5, 130, '1/2 boîte', 'co', { unitG: 250, unit: 'boîte (400 g)', units: 'boîtes (400 g)' }],
  ['mais', 'Maïs doux (boîte)', 85, 2.8, 15, 1.2, 70, '1/2 petite boîte', 'co', { unitG: 140, unit: 'petite boîte', units: 'petites boîtes' }],
  ['tomates-conc', 'Tomates concassées (boîte)', 25, 1.2, 4, 0.2, 200, '1/2 boîte', 'co', { unitG: 400, unit: 'boîte (400 g)', units: 'boîtes (400 g)' }],
  ['feta', 'Feta', 265, 14, 1, 22, 30, '1 portion', 'cr', { unitG: 200, unit: 'bloc (200 g)', units: 'blocs (200 g)' }],
  ['chevre-frais', 'Fromage de chèvre frais', 200, 11, 3, 16, 30, '1 portion', 'cr', { unitG: 150, unit: 'pot (150 g)', units: 'pots (150 g)' }],
  ['parmesan', 'Parmesan', 390, 33, 0, 28, 10, '1 c. à soupe râpé', 'cr', null],
  ['yaourt-0', 'Yaourt nature 0 %', 45, 4.5, 6, 0.1, 125, '1 pot', 'cr', { unitG: 125, unit: 'pot', units: 'pots' }],
  ['creme-legere', 'Crème légère 15 %', 160, 3, 4, 15, 30, '2 c. à soupe', 'cr', { unitG: 200, unit: 'brique (20 cl)', units: 'briques (20 cl)' }],
  ['cottage', 'Cottage cheese', 100, 11, 3.5, 4.5, 200, '1 pot', 'cr', { unitG: 200, unit: 'pot', units: 'pots' }],
  ['dinde', 'Blanc de dinde (tranches)', 105, 21, 1, 1.8, 40, '1 tranche', 'vi', { unitG: 40, unit: 'tranche', units: 'tranches' }],
  ['concombre', 'Concombre', 12, 0.6, 2, 0.1, 100, '1/3 concombre', 'fl', { unitG: 300, unit: 'concombre', units: 'concombres' }],
  ['poivron', 'Poivron', 28, 0.9, 5, 0.3, 75, '1/2 poivron', 'fl', { unitG: 150, unit: 'poivron', units: 'poivrons' }],
  ['oignon-rouge', 'Oignon rouge', 40, 1.1, 8, 0.1, 30, '1/4 oignon', 'fl', { unitG: 120, unit: 'oignon', units: 'oignons' }],
  ['epinards', 'Épinards frais', 23, 2.9, 1.4, 0.4, 50, '2 poignées', 'fl', { unitG: 250, unit: 'sachet (250 g)', units: 'sachets (250 g)' }],
  ['champignons', 'Champignons de Paris', 22, 3.1, 1.5, 0.3, 100, '4 champignons', 'fl', { unitG: 250, unit: 'barquette (250 g)', units: 'barquettes (250 g)' }],
  ['citron', 'Citron (jus)', 25, 0.4, 7, 0.2, 15, '1/2 citron', 'fl', { unitG: 40, unit: 'citron', units: 'citrons' }],
  ['chou-rouge', 'Chou rouge', 30, 1.4, 5, 0.2, 50, '1 poignée', 'fl', { unitG: 500, unit: 'demi-chou', units: 'demi-choux' }],
  ['fruits-rouges', 'Fruits rouges surgelés', 45, 0.9, 8, 0.4, 100, '1 bol', 'su', { unitG: 500, unit: 'sachet (500 g)', units: 'sachets (500 g)' }],
  ['edamame', 'Edamame surgelés', 120, 11, 9, 5, 60, '1 poignée', 'su', { unitG: 400, unit: 'sachet (400 g)', units: 'sachets (400 g)' }],
  ['semoule', 'Semoule cuite', 110, 3.8, 22, 0.3, 180, '1 assiette', 'fe', null, { name: 'Semoule (sèche)', factor: 0.4 }],
  ['houmous', 'Houmous', 300, 8, 14, 23, 50, '2 c. à soupe', 'ep', { unitG: 200, unit: 'pot (200 g)', units: 'pots (200 g)' }],
  ['pesto', 'Pesto', 450, 5, 6, 45, 15, '1 c. à soupe', 'ep', { unitG: 190, unit: 'pot', units: 'pots' }],
  ['soja', 'Sauce soja', 60, 8, 5, 0, 15, '1 c. à soupe', 'ep', null],
  ['moutarde', 'Moutarde', 150, 7, 5, 11, 10, '1 c. à café', 'ep', null]
].map(([k, name, kcal, p, c, f, portion, portionLabel, aisle, unit, buy]) => ({ id: 'ing-' + k, name, kcal, p, c, f, portion, portionLabel, base: true, aisle, ...(unit || {}), ...(buy ? { buy } : {}) }));

/* Rayon, unités d'achat et conversion cuit → cru pour les aliments de base */
D.SHOP_INFO = {
  'Flocons d\'avoine': { aisle: 'fe' },
  'Pain de mie complet': { aisle: 'bo', unitG: 500, unit: 'paquet', units: 'paquets' },
  'Baguette': { aisle: 'bo', unitG: 250, unit: 'baguette', units: 'baguettes' },
  'Œuf entier': { aisle: 'cr', unitG: 60, unit: 'œuf', units: 'œufs' },
  'Blanc de poulet cuit': { aisle: 'vi', buy: { name: 'Blanc de poulet (cru)', factor: 1.3 } },
  'Cuisse de poulet rôtie': { aisle: 'vi' },
  'Steak haché 5 % (cuit)': { aisle: 'vi', buy: { name: 'Bœuf haché 5 % (cru)', factor: 1.25 } },
  'Saumon cuit': { aisle: 'vi', buy: { name: 'Pavé de saumon (cru)', factor: 1.2 } },
  'Cabillaud cuit': { aisle: 'vi', buy: { name: 'Dos de cabillaud (cru)', factor: 1.2 } },
  'Thon au naturel': { aisle: 'co', unitG: 112, unit: 'boîte (égouttée 112 g)', units: 'boîtes (égouttées 112 g)' },
  'Crevettes cuites': { aisle: 'vi' },
  'Jambon blanc': { aisle: 'vi', unitG: 45, unit: 'tranche', units: 'tranches' },
  'Tofu nature': { aisle: 'cr' },
  'Riz basmati cuit': { aisle: 'fe', buy: { name: 'Riz basmati (sec)', factor: 0.4 } },
  'Pâtes cuites': { aisle: 'fe', buy: { name: 'Pâtes (sèches)', factor: 0.42 } },
  'Quinoa cuit': { aisle: 'fe', buy: { name: 'Quinoa (sec)', factor: 0.4 } },
  'Pomme de terre cuite': { aisle: 'fl', buy: { name: 'Pommes de terre', factor: 1 } },
  'Patate douce cuite': { aisle: 'fl', buy: { name: 'Patates douces', factor: 1.1 } },
  'Lentilles cuites': { aisle: 'fe', buy: { name: 'Lentilles (sèches)', factor: 0.4 } },
  'Petits pois': { aisle: 'su' },
  'Haricots verts': { aisle: 'su' },
  'Brocoli cuit': { aisle: 'fl', buy: { name: 'Brocoli', factor: 1 } },
  'Courgette cuite': { aisle: 'fl', buy: { name: 'Courgettes', factor: 1.1 } },
  'Carottes': { aisle: 'fl' },
  'Tomate': { aisle: 'fl', unitG: 120, unit: 'tomate', units: 'tomates' },
  'Salade verte': { aisle: 'fl', unitG: 150, unit: 'salade / sachet', units: 'salades / sachets' },
  'Soupe de légumes': { aisle: 'co' },
  'Banane': { aisle: 'fl', unitG: 120, unit: 'banane', units: 'bananes' },
  'Pomme': { aisle: 'fl', unitG: 150, unit: 'pomme', units: 'pommes' },
  'Avocat': { aisle: 'fl', unitG: 150, unit: 'avocat', units: 'avocats' },
  'Skyr nature': { aisle: 'cr', unitG: 150, unit: 'pot (150 g)', units: 'pots (150 g)' },
  'Fromage blanc 0 %': { aisle: 'cr' },
  'Yaourt grec': { aisle: 'cr', unitG: 150, unit: 'pot', units: 'pots' },
  'Lait demi-écrémé': { aisle: 'cr' },
  'Emmental': { aisle: 'cr' },
  'Mozzarella': { aisle: 'cr', unitG: 125, unit: 'boule', units: 'boules' },
  'Huile d\'olive': { aisle: 'pl' },
  'Beurre de cacahuète': { aisle: 'ep' },
  'Amandes': { aisle: 'ep' },
  'Whey protéine': { aisle: 'ep' },
  'Chocolat noir 70 %': { aisle: 'ep' },
  'Miel': { aisle: 'pl' },
  'Muesli': { aisle: 'fe' },
  'Galettes de riz': { aisle: 'fe' }
};

D.RECIPE_CATS = [
  { id: 'wrap', label: 'Wraps', icon: 'repeat' },
  { id: 'salade', label: 'Salades', icon: 'food' },
  { id: 'bowl', label: 'Bowls', icon: 'pot' },
  { id: 'plat', label: 'Plats chauds', icon: 'flame' },
  { id: 'gratin', label: 'Gratins & hachis', icon: 'grid' },
  { id: 'petitdej', label: 'Petit-déj', icon: 'sun' },
  { id: 'collation', label: 'Collations', icon: 'star' }
];
D.RECIPE_TAGS = {
  proteine: 'Riche en protéines', rapide: '≤ 15 min', lunchbox: 'Lunchbox', batch: 'Batch cooking', froid: 'Sans cuisson', vege: 'Végétarien'
};

/* Raccourci : nom d'aliment → identifiant */
const R_ = (name, g) => ({ name, g });
D.BASE_RECIPES = [
  // ---------- Wraps ----------
  { id: 'r-wrap-cesar', name: 'Wrap poulet César allégé', cat: 'wrap', time: 15, tags: ['lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla complète (wrap)', 120), R_('Blanc de poulet cuit', 150), R_('Salade verte', 40), R_('Parmesan', 10), R_('Yaourt nature 0 %', 40), R_('Moutarde', 5), R_('Citron (jus)', 10)],
    pantry: ['Ail', 'Poivre'],
    steps: ['Mélange le yaourt, la moutarde, le jus de citron, un peu d\'ail râpé et du poivre : c\'est la sauce César allégée.', 'Tranche le poulet en lamelles et cisèle la salade.', 'Étale la sauce sur les tortillas, ajoute salade, poulet et parmesan, puis roule serré.', 'Coupe en deux en biais. Se garde 24 h au frais, emballé dans du papier aluminium.'],
    tip: 'La sauce au yaourt remplace la mayonnaise : environ 150 kcal économisées sans perdre le goût.' },
  { id: 'r-wrap-thon', name: 'Wrap thon, avocat & maïs', cat: 'wrap', time: 10, tags: ['froid', 'lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla de blé (wrap)', 120), R_('Thon au naturel', 110), R_('Avocat', 50), R_('Maïs doux (boîte)', 40), R_('Concombre', 60), R_('Yaourt nature 0 %', 30)],
    pantry: ['Paprika', 'Sel, poivre'],
    steps: ['Égoutte le thon et mélange-le avec le yaourt, une pincée de paprika, sel et poivre.', 'Écrase l\'avocat sur les tortillas.', 'Ajoute le thon, le maïs et le concombre en bâtonnets, puis roule.'],
    tip: 'Sans cuisson et prêt en 10 minutes : l\'idéal les jours de cours ou de chantier.' },
  { id: 'r-wrap-houmous', name: 'Wrap houmous, pois chiches & feta', cat: 'wrap', time: 10, tags: ['froid', 'vege', 'lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla complète (wrap)', 120), R_('Houmous', 40), R_('Pois chiches cuits', 100), R_('Feta', 30), R_('Poivron', 60), R_('Salade verte', 30)],
    pantry: ['Cumin'],
    steps: ['Rince les pois chiches et écrase-les grossièrement à la fourchette avec une pincée de cumin.', 'Tartine les tortillas de houmous, ajoute pois chiches, feta émiettée, poivron en lamelles et salade.', 'Roule serré.'],
    tip: 'Version végétarienne : accompagne-la d\'un skyr pour compléter les protéines.' },
  { id: 'r-wrap-dinde', name: 'Wrap dinde & chèvre frais express', cat: 'wrap', time: 5, tags: ['froid', 'lunchbox'], slots: ['lunch', 'dinner', 'snack'],
    ing: [R_('Tortilla de blé (wrap)', 120), R_('Blanc de dinde (tranches)', 120), R_('Fromage de chèvre frais', 30), R_('Épinards frais', 30), R_('Tomate', 60)],
    pantry: ['Herbes de Provence'],
    steps: ['Tartine les tortillas de chèvre frais et parsème d\'herbes.', 'Ajoute la dinde, les pousses d\'épinard et la tomate en rondelles.', 'Roule et coupe en deux.'],
    tip: 'Le plus rapide de la liste : 5 minutes, idéal la veille au soir.' },
  { id: 'r-wrap-fajitas', name: 'Wraps bœuf façon fajitas', cat: 'wrap', time: 20, tags: [], slots: ['dinner', 'lunch'],
    ing: [R_('Tortilla de blé (wrap)', 120), R_('Steak haché 5 % (cuit)', 125), R_('Poivron', 100), R_('Oignon rouge', 50), R_('Haricots rouges cuits', 50), R_('Emmental', 20)],
    pantry: ['Épices fajitas ou paprika + cumin', 'Huile en spray'],
    steps: ['Fais revenir oignon et poivron émincés 5 min dans une poêle légèrement huilée.', 'Ajoute la viande hachée et les épices, cuis 5 min, puis les haricots rouges rincés.', 'Garnis les tortillas chaudes, parsème d\'emmental et roule.'],
    tip: 'Prépare la garniture en double : elle se réchauffe très bien le lendemain.' },
  { id: 'r-wrap-oeufs', name: 'Wrap œufs brouillés & épinards', cat: 'petitdej', time: 10, tags: ['rapide'], slots: ['breakfast'],
    ing: [R_('Tortilla de blé (wrap)', 60), R_('Œuf entier', 120), R_('Épinards frais', 30), R_('Emmental', 20)],
    pantry: ['Sel, poivre'],
    steps: ['Fais tomber les épinards 1 min dans une poêle.', 'Ajoute les œufs battus et remue doucement jusqu\'à ce qu\'ils soient crémeux.', 'Garnis la tortilla, ajoute l\'emmental et roule.'],
    tip: 'Un petit-déjeuner salé et protéiné tient souvent mieux jusqu\'au midi.' },

  // ---------- Salades ----------
  { id: 'r-sal-grecque', name: 'Salade grecque au poulet & quinoa', cat: 'salade', time: 15, tags: ['lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Blanc de poulet cuit', 130), R_('Quinoa cuit', 100), R_('Concombre', 120), R_('Tomate', 120), R_('Oignon rouge', 30), R_('Feta', 40), R_('Huile d\'olive', 8), R_('Citron (jus)', 10)],
    pantry: ['Origan', 'Olives (facultatif)'],
    steps: ['Fais cuire le quinoa (ou utilise celui préparé en avance) et laisse refroidir.', 'Coupe concombre, tomate et oignon en dés, le poulet en morceaux.', 'Mélange le tout avec la feta émiettée, l\'huile, le citron et l\'origan.'],
    tip: 'Dans une boîte, mets la vinaigrette au fond et la salade dessus : rien ne ramollit.' },
  { id: 'r-sal-lentilles', name: 'Salade lentilles, thon & œuf', cat: 'salade', time: 15, tags: ['lunchbox', 'batch'], slots: ['lunch', 'dinner'],
    ing: [R_('Lentilles cuites', 180), R_('Thon au naturel', 80), R_('Œuf entier', 60), R_('Carottes', 80), R_('Oignon rouge', 20), R_('Moutarde', 10), R_('Huile d\'olive', 8)],
    pantry: ['Vinaigre', 'Persil'],
    steps: ['Fais cuire l\'œuf 9 min (dur), refroidis et écale.', 'Râpe les carottes, émince l\'oignon.', 'Mélange lentilles, carottes, oignon et thon ; assaisonne avec moutarde, huile et vinaigre.', 'Ajoute l\'œuf coupé en quartiers.'],
    tip: 'Les lentilles apportent fibres et protéines : très rassasiant pour un coût faible.' },
  { id: 'r-sal-pates-pesto', name: 'Salade de pâtes pesto, poulet & mozzarella', cat: 'salade', time: 20, tags: ['lunchbox', 'batch'], slots: ['lunch'],
    ing: [R_('Pâtes cuites', 180), R_('Blanc de poulet cuit', 110), R_('Mozzarella', 50), R_('Tomate', 100), R_('Pesto', 15), R_('Salade verte', 20)],
    pantry: ['Basilic'],
    steps: ['Cuis les pâtes, rince-les à l\'eau froide.', 'Mélange avec le pesto, puis ajoute poulet, mozzarella et tomates en dés.', 'Ajoute la roquette ou la salade au moment de manger.'],
    tip: 'À préparer le dimanche pour 2 ou 3 midis.' },
  { id: 'r-sal-riz-thon', name: 'Salade riz, thon & maïs', cat: 'salade', time: 15, tags: ['lunchbox', 'batch'], slots: ['lunch'],
    ing: [R_('Riz basmati cuit', 180), R_('Thon au naturel', 100), R_('Maïs doux (boîte)', 60), R_('Tomate', 100), R_('Œuf entier', 60), R_('Poivron', 60), R_('Huile d\'olive', 8), R_('Yaourt nature 0 %', 30)],
    pantry: ['Sel, poivre'],
    steps: ['Cuis le riz et l\'œuf (9 min), laisse refroidir.', 'Coupe tomate, poivron et œuf.', 'Mélange tout avec le thon, le maïs, l\'huile et le yaourt.'],
    tip: 'Le classique qui plaît à tout le monde, en version plus protéinée.' },
  { id: 'r-sal-crevettes', name: 'Salade crevettes, avocat & agrumes', cat: 'salade', time: 10, tags: ['froid', 'rapide'], slots: ['lunch', 'dinner'],
    ing: [R_('Crevettes cuites', 150), R_('Avocat', 60), R_('Salade verte', 60), R_('Concombre', 80), R_('Maïs doux (boîte)', 40), R_('Citron (jus)', 15), R_('Huile d\'olive', 5), R_('Pain de mie complet', 50)],
    pantry: ['Piment d\'Espelette'],
    steps: ['Décortique les crevettes si besoin.', 'Dispose salade, concombre, avocat et maïs.', 'Ajoute les crevettes, arrose de citron et d\'huile, sers avec le pain grillé.'],
    tip: 'Léger mais riche en protéines : parfait un soir sans entraînement.' },
  { id: 'r-sal-taboule', name: 'Taboulé au poulet', cat: 'salade', time: 15, tags: ['lunchbox', 'batch'], slots: ['lunch', 'dinner'],
    ing: [R_('Semoule cuite', 180), R_('Blanc de poulet cuit', 120), R_('Tomate', 100), R_('Concombre', 100), R_('Citron (jus)', 15), R_('Huile d\'olive', 8), R_('Oignon rouge', 20)],
    pantry: ['Menthe', 'Persil'],
    steps: ['Verse de l\'eau bouillante sur la semoule (même volume), couvre 5 min puis égraine.', 'Ajoute tomates, concombre et oignon en petits dés, menthe et persil ciselés.', 'Assaisonne avec citron et huile, puis ajoute le poulet.'],
    tip: 'Meilleur après une nuit au frais : parfait en batch cooking.' },

  // ---------- Bowls ----------
  { id: 'r-bowl-poke', name: 'Poke bowl saumon', cat: 'bowl', time: 20, tags: [], slots: ['lunch', 'dinner'],
    ing: [R_('Riz basmati cuit', 180), R_('Saumon cuit', 120), R_('Edamame surgelés', 60), R_('Concombre', 60), R_('Avocat', 40), R_('Chou rouge', 40), R_('Sauce soja', 15)],
    pantry: ['Graines de sésame', 'Gingembre'],
    steps: ['Cuis le riz et laisse tiédir.', 'Saisis le saumon 3 min par face (ou utilise du saumon déjà cuit), coupe-le en cubes.', 'Plonge les edamame 3 min dans l\'eau bouillante.', 'Dispose tout sur le riz, arrose de sauce soja et parsème de sésame.'],
    tip: 'Le saumon apporte des oméga-3, utiles pour la récupération.' },
  { id: 'r-bowl-teriyaki', name: 'Bowl poulet teriyaki & brocoli', cat: 'bowl', time: 20, tags: ['proteine', 'batch'], slots: ['lunch', 'dinner'],
    ing: [R_('Riz basmati cuit', 180), R_('Blanc de poulet cuit', 150), R_('Brocoli cuit', 150), R_('Sauce soja', 15), R_('Miel', 10)],
    pantry: ['Ail', 'Gingembre', 'Huile en spray'],
    steps: ['Mélange sauce soja, miel, ail et gingembre râpés.', 'Fais dorer le poulet en dés, ajoute la sauce et laisse caraméliser 2 min.', 'Cuis le brocoli 5 min à la vapeur.', 'Sers sur le riz.'],
    tip: 'Environ 55 g de protéines : l\'un des repas les plus efficaces de la liste.' },
  { id: 'r-bowl-chili', name: 'Chili con carne & riz', cat: 'plat', time: 35, tags: ['batch', 'proteine'], slots: ['dinner', 'lunch'],
    ing: [R_('Steak haché 5 % (cuit)', 125), R_('Haricots rouges cuits', 100), R_('Tomates concassées (boîte)', 150), R_('Maïs doux (boîte)', 40), R_('Oignon rouge', 50), R_('Riz basmati cuit', 150)],
    pantry: ['Cumin', 'Paprika', 'Piment', 'Ail'],
    steps: ['Fais revenir l\'oignon émincé, ajoute la viande et fais-la dorer.', 'Ajoute les épices, les tomates, les haricots rincés et le maïs.', 'Laisse mijoter 20 min à feu doux.', 'Sers avec le riz.'],
    tip: 'Prévu pour le batch cooking : prépare 4 portions et congèle-en 2.' },

  // ---------- Plats chauds ----------
  { id: 'r-plat-curry', name: 'Curry de poulet express & riz', cat: 'plat', time: 25, tags: ['proteine', 'batch'], slots: ['dinner', 'lunch'],
    ing: [R_('Blanc de poulet cuit', 150), R_('Crème légère 15 %', 40), R_('Tomates concassées (boîte)', 100), R_('Oignon rouge', 40), R_('Épinards frais', 50), R_('Riz basmati cuit', 180)],
    pantry: ['Curry en poudre', 'Ail', 'Gingembre'],
    steps: ['Fais revenir l\'oignon avec l\'ail et le curry 2 min.', 'Ajoute le poulet en dés, fais dorer.', 'Verse les tomates et la crème, laisse mijoter 10 min, ajoute les épinards à la fin.', 'Sers avec le riz.'],
    tip: 'La crème légère donne l\'onctuosité avec deux fois moins de lipides que la crème entière.' },
  { id: 'r-plat-saumon', name: 'Saumon, patate douce rôtie & haricots verts', cat: 'plat', time: 30, tags: [], slots: ['dinner'],
    ing: [R_('Saumon cuit', 130), R_('Patate douce cuite', 220), R_('Haricots verts', 150), R_('Huile d\'olive', 5)],
    pantry: ['Paprika fumé', 'Sel, poivre'],
    steps: ['Coupe la patate douce en cubes, mélange avec l\'huile et le paprika, enfourne 25 min à 200 °C.', 'Cuis les haricots verts 8 min à la vapeur.', 'Saisis le saumon 4 min côté peau puis 2 min de l\'autre côté.'],
    tip: 'Un dîner complet, riche en fibres et en bonnes graisses.' },
  { id: 'r-plat-cabillaud', name: 'Cabillaud, pommes de terre & brocoli au citron', cat: 'plat', time: 25, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Cabillaud cuit', 180), R_('Pomme de terre cuite', 250), R_('Brocoli cuit', 150), R_('Huile d\'olive', 8), R_('Citron (jus)', 10)],
    pantry: ['Aneth ou persil'],
    steps: ['Cuis les pommes de terre 20 min à l\'eau.', 'Cuis le brocoli 5 min à la vapeur.', 'Poêle le cabillaud 3 min par face.', 'Arrose d\'huile, de citron et d\'herbes.'],
    tip: 'Très rassasiant pour peu de calories : utile les soirs de grosse faim.' },
  { id: 'r-plat-bolo', name: 'Pâtes bolognaise protéinées', cat: 'plat', time: 25, tags: ['batch', 'proteine'], slots: ['dinner', 'lunch'],
    ing: [R_('Pâtes cuites', 200), R_('Steak haché 5 % (cuit)', 125), R_('Tomates concassées (boîte)', 150), R_('Oignon rouge', 40), R_('Parmesan', 10)],
    pantry: ['Ail', 'Herbes de Provence'],
    steps: ['Fais revenir l\'oignon et l\'ail, ajoute la viande et fais-la dorer.', 'Ajoute les tomates et les herbes, laisse mijoter 15 min.', 'Sers sur les pâtes avec le parmesan.'],
    tip: 'Le bœuf 5 % garde le goût de la bolognaise avec beaucoup moins de gras.' },
  { id: 'r-plat-omelette', name: 'Omelette champignons, épinards & feta', cat: 'plat', time: 15, tags: ['vege', 'rapide'], slots: ['dinner', 'lunch', 'breakfast'],
    ing: [R_('Œuf entier', 180), R_('Champignons de Paris', 100), R_('Épinards frais', 60), R_('Feta', 25), R_('Pain de mie complet', 60)],
    pantry: ['Huile en spray', 'Poivre'],
    steps: ['Fais sauter les champignons émincés 4 min, ajoute les épinards 1 min.', 'Verse les œufs battus, laisse prendre à feu moyen.', 'Émiette la feta, plie l\'omelette et sers avec le pain grillé.'],
    tip: 'Prête en 15 min avec ce qui reste au frigo.' },

  // ---------- Petit-déjeuners ----------
  { id: 'r-pdj-oats', name: 'Overnight oats protéinés', cat: 'petitdej', time: 5, tags: ['froid', 'batch'], slots: ['breakfast'],
    ing: [R_('Flocons d\'avoine', 60), R_('Lait demi-écrémé', 150), R_('Skyr nature', 100), R_('Fruits rouges surgelés', 80), R_('Whey protéine', 15)],
    pantry: ['Cannelle'],
    steps: ['La veille, mélange flocons, lait, skyr, whey et cannelle dans un bocal.', 'Ajoute les fruits rouges encore surgelés sur le dessus.', 'Ferme et laisse une nuit au frigo. Se mange froid.'],
    tip: 'Prépare 3 bocaux d\'un coup : le petit-déjeuner est prêt pour plusieurs matins.' },
  { id: 'r-pdj-pancakes', name: 'Pancakes banane & avoine', cat: 'petitdej', time: 15, tags: [], slots: ['breakfast'],
    ing: [R_('Flocons d\'avoine', 50), R_('Œuf entier', 120), R_('Banane', 100), R_('Fromage blanc 0 %', 100)],
    pantry: ['Levure chimique', 'Cannelle'],
    steps: ['Mixe les flocons, les œufs, la banane et une pincée de levure.', 'Cuis de petites louches 2 min par face dans une poêle antiadhésive.', 'Sers avec le fromage blanc.'],
    tip: 'Sans sucre ajouté : la banane suffit à sucrer.' },
  { id: 'r-pdj-skyr', name: 'Bol skyr, muesli & fruits rouges', cat: 'petitdej', time: 3, tags: ['froid', 'rapide', 'vege'], slots: ['breakfast', 'snack'],
    ing: [R_('Skyr nature', 250), R_('Muesli', 40), R_('Fruits rouges surgelés', 100), R_('Miel', 10)],
    pantry: [],
    steps: ['Verse le skyr dans un bol.', 'Ajoute les fruits rouges (décongelés au micro-ondes 1 min si besoin), le muesli et le miel.'],
    tip: '30 g de protéines en 3 minutes.' },
  { id: 'r-pdj-tartines', name: 'Tartines œufs & avocat', cat: 'petitdej', time: 10, tags: ['vege', 'rapide'], slots: ['breakfast'],
    ing: [R_('Pain de mie complet', 80), R_('Œuf entier', 120), R_('Avocat', 50)],
    pantry: ['Piment d\'Espelette', 'Sel'],
    steps: ['Fais griller le pain.', 'Cuis les œufs au plat ou mollets (6 min).', 'Écrase l\'avocat sur les tartines, ajoute les œufs et le piment.'],
    tip: 'Le week-end, c\'est le brunch express.' },

  // ---------- Collations ----------
  { id: 'r-col-shake', name: 'Shake récup banane & whey', cat: 'collation', time: 3, tags: ['rapide', 'proteine'], slots: ['snack'],
    ing: [R_('Whey protéine', 30), R_('Lait demi-écrémé', 250), R_('Banane', 120)],
    pantry: [],
    steps: ['Mixe tout 30 secondes.', 'À boire dans l\'heure qui suit la séance, ou en collation.'],
    tip: 'Pratique après une séance de renforcement pour atteindre ta cible de protéines.' },
  { id: 'r-col-cottage', name: 'Cottage cheese, fruits rouges & amandes', cat: 'collation', time: 3, tags: ['rapide', 'froid', 'vege'], slots: ['snack', 'breakfast'],
    ing: [R_('Cottage cheese', 200), R_('Fruits rouges surgelés', 100), R_('Amandes', 15)],
    pantry: [],
    steps: ['Mélange le cottage cheese et les fruits rouges.', 'Parsème d\'amandes concassées.'],
    tip: 'Une collation du soir riche en protéines, peu sucrée.' },
  { id: 'r-col-houmous', name: 'Houmous & crudités', cat: 'collation', time: 5, tags: ['rapide', 'froid', 'vege'], slots: ['snack'],
    ing: [R_('Houmous', 60), R_('Carottes', 100), R_('Concombre', 100), R_('Galettes de riz', 20)],
    pantry: [],
    steps: ['Coupe carottes et concombre en bâtonnets.', 'Sers avec le houmous et les galettes de riz.'],
    tip: 'Du croquant et des fibres pour tenir jusqu\'au dîner.' },
  { id: 'r-col-roules', name: 'Roulés de dinde au chèvre frais', cat: 'collation', time: 5, tags: ['rapide', 'froid', 'proteine'], slots: ['snack'],
    ing: [R_('Blanc de dinde (tranches)', 100), R_('Fromage de chèvre frais', 30), R_('Concombre', 80)],
    pantry: ['Ciboulette'],
    steps: ['Tartine les tranches de dinde de chèvre frais et de ciboulette.', 'Ajoute un bâtonnet de concombre et roule.'],
    tip: '25 g de protéines pour moins de 200 kcal.' }
];


/* ======================================================================
   Extension : ingrédients et recettes supplémentaires.
   Pour ajouter tes propres recettes au code, copie un bloc ci-dessous :
   les noms d'ingrédients doivent correspondre exactement à un aliment de la base.
   ====================================================================== */
D.EXTRA_FOODS.push(...[
  ['aubergine', 'Aubergine', 25, 1, 4.5, 0.2, 150, '1/2 aubergine', 'fl', { unitG: 300, unit: 'aubergine', units: 'aubergines' }],
  ['poireau', 'Poireau', 30, 1.5, 5, 0.3, 150, '1 poireau', 'fl', { unitG: 200, unit: 'poireau', units: 'poireaux' }],
  ['chou-fleur', 'Chou-fleur', 25, 1.9, 3, 0.3, 250, '1/4 chou-fleur', 'fl', { unitG: 700, unit: 'chou-fleur', units: 'choux-fleurs' }],
  ['butternut', 'Courge butternut', 40, 1, 8, 0.1, 300, '1/4 courge', 'fl', { unitG: 1200, unit: 'courge', units: 'courges' }],
  ['betterave', 'Betterave cuite', 45, 1.6, 8.5, 0.1, 100, '1 betterave', 'fl', { unitG: 250, unit: 'barquette (250 g)', units: 'barquettes (250 g)' }],
  ['escalope-dinde', 'Escalope de dinde cuite', 135, 29, 0, 2, 150, '1 escalope', 'vi', null, { name: 'Escalopes de dinde (crues)', factor: 1.3 }],
  ['filet-mignon', 'Filet mignon de porc cuit', 160, 28, 0, 5, 150, '1 portion', 'vi', null, { name: 'Filet mignon de porc (cru)', factor: 1.3 }],
  ['saumon-fume', 'Saumon fumé', 180, 22, 0, 10, 80, '2 tranches', 'vi', { unitG: 40, unit: 'tranche', units: 'tranches' }],
  ['surimi', 'Surimi', 100, 8, 14, 1.5, 100, '6 bâtonnets', 'vi', null],
  ['fromage-frais', 'Fromage frais allégé', 110, 8, 6, 5, 40, '2 c. à soupe', 'cr', { unitG: 150, unit: 'pot (150 g)', units: 'pots (150 g)' }],
  ['ricotta', 'Ricotta', 150, 9, 4, 11, 50, '2 c. à soupe', 'cr', { unitG: 250, unit: 'pot (250 g)', units: 'pots (250 g)' }],
  ['buche-chevre', 'Bûche de chèvre', 300, 19, 1, 25, 40, '2 rondelles', 'cr', { unitG: 180, unit: 'bûche (180 g)', units: 'bûches (180 g)' }],
  ['pita', 'Pain pita', 275, 9, 55, 1.2, 70, '1 pita', 'bo', { unitG: 70, unit: 'pita', units: 'pitas' }],
  ['boulgour', 'Boulgour cuit', 110, 3.5, 20, 0.3, 150, '1 assiette', 'fe', null, { name: 'Boulgour (sec)', factor: 0.42 }],
  ['nouilles', 'Nouilles de riz cuites', 110, 1.8, 24, 0.2, 180, '1 assiette', 'fe', null, { name: 'Nouilles de riz (sèches)', factor: 0.4 }],
  ['olives', 'Olives noires', 150, 1, 3, 15, 15, '5 olives', 'co', null],
  ['lait-coco', 'Lait de coco léger', 70, 0.7, 2, 7, 60, '4 c. à soupe', 'co', { unitG: 200, unit: 'brique (20 cl)', units: 'briques (20 cl)' }],
  ['noix', 'Cerneaux de noix', 650, 15, 7, 65, 10, '1 petite poignée', 'ep', null]
].map(([k, name, kcal, p, c, f, portion, portionLabel, aisle, unit, buy]) => ({ id: 'ing-' + k, name, kcal, p, c, f, portion, portionLabel, base: true, aisle, ...(unit || {}), ...(buy ? { buy } : {}) })));

D.BASE_RECIPES.push(
  // ---------- Salades ----------
  { id: 'r-sal-chevre', name: 'Salade chèvre chaud, betterave & noix', cat: 'salade', time: 15, tags: [], slots: ['lunch', 'dinner'],
    ing: [R_('Salade verte', 80), R_('Bûche de chèvre', 40), R_('Blanc de dinde (tranches)', 60), R_('Betterave cuite', 100), R_('Pain de mie complet', 40), R_('Cerneaux de noix', 10), R_('Huile d\'olive', 5)],
    pantry: ['Vinaigre balsamique', 'Miel (facultatif)'],
    steps: ['Dispose 2 rondelles de chèvre sur le pain et passe 5 min au four (ou 1 min au micro-ondes).', 'Coupe la betterave en dés et la dinde en lanières.', 'Assaisonne la salade (huile + balsamique), ajoute betterave, dinde, noix et les toasts chauds.'],
    tip: 'Une portion raisonnable de chèvre suffit : le goût est puissant, inutile d\'en mettre beaucoup.' },
  { id: 'r-sal-nicoise', name: 'Salade niçoise au thon', cat: 'salade', time: 20, tags: ['lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Thon au naturel', 120), R_('Œuf entier', 60), R_('Haricots verts', 100), R_('Pomme de terre cuite', 150), R_('Tomate', 100), R_('Olives noires', 15), R_('Salade verte', 50), R_('Huile d\'olive', 8)],
    pantry: ['Vinaigre', 'Sel, poivre'],
    steps: ['Cuis pommes de terre (20 min) et haricots verts (8 min), l\'œuf 9 min. Laisse refroidir.', 'Coupe tomates, pommes de terre et œuf.', 'Dispose tout sur la salade avec le thon et les olives, assaisonne.'],
    tip: 'Cuis les pommes de terre et les haricots la veille : l\'assemblage prend 5 minutes.' },
  { id: 'r-sal-poischiches', name: 'Salade pois chiches, concombre & feta', cat: 'salade', time: 10, tags: ['froid', 'vege', 'lunchbox', 'rapide'], slots: ['lunch', 'dinner'],
    ing: [R_('Pois chiches cuits', 150), R_('Concombre', 100), R_('Tomate', 100), R_('Feta', 40), R_('Oignon rouge', 20), R_('Huile d\'olive', 8), R_('Citron (jus)', 10), R_('Skyr nature', 100)],
    pantry: ['Menthe', 'Cumin'],
    steps: ['Rince les pois chiches.', 'Coupe concombre, tomate et oignon en dés.', 'Mélange avec la feta, l\'huile, le citron et la menthe. Sers avec le skyr assaisonné en sauce.'],
    tip: 'Le skyr en sauce ajoute 10 g de protéines à une salade végétarienne.' },
  { id: 'r-sal-surimi', name: 'Salade riz, surimi & avocat', cat: 'salade', time: 15, tags: ['lunchbox', 'froid'], slots: ['lunch'],
    ing: [R_('Riz basmati cuit', 150), R_('Surimi', 120), R_('Avocat', 50), R_('Concombre', 80), R_('Maïs doux (boîte)', 40), R_('Yaourt nature 0 %', 40), R_('Blanc de poulet cuit', 50)],
    pantry: ['Citron vert', 'Sauce soja'],
    steps: ['Cuis le riz et laisse refroidir.', 'Coupe le surimi en tronçons, l\'avocat et le concombre en dés.', 'Mélange avec le maïs, le poulet et le yaourt citronné.'],
    tip: 'Façon « california roll » en saladier, prête pour la gamelle.' },
  { id: 'r-sal-boulgour', name: 'Salade boulgour, poulet & légumes grillés', cat: 'salade', time: 25, tags: ['lunchbox', 'batch'], slots: ['lunch', 'dinner'],
    ing: [R_('Boulgour cuit', 150), R_('Blanc de poulet cuit', 120), R_('Courgette cuite', 100), R_('Poivron', 80), R_('Feta', 20), R_('Huile d\'olive', 8), R_('Citron (jus)', 10)],
    pantry: ['Persil', 'Paprika'],
    steps: ['Cuis le boulgour 12 min dans l\'eau bouillante.', 'Fais griller courgette et poivron en lamelles 8 min à la poêle.', 'Mélange tout avec le poulet, la feta, l\'huile et le citron.'],
    tip: 'Se garde 3 jours au frais : idéal en batch cooking.' },
  { id: 'r-sal-saumonfume', name: 'Salade saumon fumé, pommes de terre & avocat', cat: 'salade', time: 20, tags: [], slots: ['lunch', 'dinner'],
    ing: [R_('Saumon fumé', 80), R_('Pomme de terre cuite', 180), R_('Avocat', 40), R_('Salade verte', 50), R_('Yaourt nature 0 %', 40), R_('Citron (jus)', 10), R_('Œuf entier', 60)],
    pantry: ['Aneth', 'Ciboulette'],
    steps: ['Cuis les pommes de terre et l\'œuf, laisse tiédir.', 'Mélange yaourt, citron et aneth pour la sauce.', 'Dispose salade, pommes de terre, avocat, saumon et œuf, nappe de sauce.'],
    tip: 'Le saumon fumé est salé : pas besoin d\'ajouter de sel.' },
  { id: 'r-sal-coleslaw', name: 'Coleslaw croquant au poulet', cat: 'salade', time: 15, tags: ['froid', 'lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Chou rouge', 100), R_('Carottes', 100), R_('Yaourt nature 0 %', 50), R_('Moutarde', 5), R_('Blanc de poulet cuit', 130), R_('Pain de mie complet', 50)],
    pantry: ['Vinaigre de cidre'],
    steps: ['Râpe finement le chou et les carottes.', 'Mélange yaourt, moutarde et un filet de vinaigre, assaisonne les légumes.', 'Ajoute le poulet en lanières, sers avec le pain.'],
    tip: 'Version légère du coleslaw : le yaourt remplace la mayonnaise.' },
  { id: 'r-sal-lentilles-betterave', name: 'Salade lentilles, betterave & œuf', cat: 'salade', time: 15, tags: ['lunchbox', 'vege'], slots: ['lunch', 'dinner'],
    ing: [R_('Lentilles cuites', 180), R_('Betterave cuite', 100), R_('Fromage de chèvre frais', 30), R_('Salade verte', 30), R_('Cerneaux de noix', 10), R_('Œuf entier', 120)],
    pantry: ['Vinaigre', 'Moutarde'],
    steps: ['Cuis les œufs 9 min.', 'Mélange lentilles, betterave en dés et salade.', 'Ajoute le chèvre émietté, les noix et les œufs en quartiers, assaisonne.'],
    tip: 'Fibres, fer et protéines végétales : très rassasiant pour peu de calories.' },

  // ---------- Wraps ----------
  { id: 'r-wrap-saumon', name: 'Wrap saumon fumé & fromage frais', cat: 'wrap', time: 5, tags: ['froid', 'rapide', 'lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla de blé (wrap)', 120), R_('Saumon fumé', 80), R_('Fromage frais allégé', 40), R_('Concombre', 60), R_('Salade verte', 20)],
    pantry: ['Aneth', 'Citron'],
    steps: ['Tartine les tortillas de fromage frais.', 'Ajoute le saumon, le concombre en bâtonnets et la salade.', 'Roule serré et coupe en deux.'],
    tip: 'Prêt en 5 minutes, sans cuisson.' },
  { id: 'r-wrap-curry', name: 'Wrap poulet curry & crudités', cat: 'wrap', time: 10, tags: ['froid', 'lunchbox', 'rapide'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla complète (wrap)', 120), R_('Blanc de poulet cuit', 130), R_('Yaourt nature 0 %', 40), R_('Carottes', 60), R_('Salade verte', 30)],
    pantry: ['Curry en poudre'],
    steps: ['Mélange le yaourt avec 1 c. à café de curry.', 'Enrobe le poulet en lanières de sauce curry.', 'Garnis les tortillas de carottes râpées, salade et poulet, puis roule.'],
    tip: 'Parfait pour finir un reste de poulet rôti.' },
  { id: 'r-wrap-omelette', name: 'Wrap omelette & jambon', cat: 'wrap', time: 10, tags: ['rapide'], slots: ['breakfast', 'lunch'],
    ing: [R_('Tortilla de blé (wrap)', 60), R_('Œuf entier', 120), R_('Jambon blanc', 45), R_('Emmental', 15), R_('Salade verte', 20)],
    pantry: ['Huile en spray'],
    steps: ['Bats les œufs et verse-les dans une poêle chaude de la taille de la tortilla.', 'Pose la tortilla sur l\'omelette encore baveuse 30 s, puis retourne le tout.', 'Garnis de jambon, emmental et salade, roule.'],
    tip: 'L\'omelette se colle à la tortilla : un wrap chaud en une seule poêle.' },
  { id: 'r-wrap-burrito', name: 'Burrito maison bœuf, riz & haricots', cat: 'wrap', time: 20, tags: ['batch'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla de blé (wrap)', 120), R_('Steak haché 5 % (cuit)', 110), R_('Riz basmati cuit', 80), R_('Haricots rouges cuits', 60), R_('Tomate', 60), R_('Emmental', 15)],
    pantry: ['Cumin', 'Paprika', 'Piment'],
    steps: ['Fais dorer la viande avec les épices, ajoute les haricots rincés 2 min.', 'Garnis les tortillas de riz, viande, tomate en dés et emmental.', 'Replie les bords puis roule. Se réchauffe 1 min au micro-ondes.'],
    tip: 'Prépare-en 4 d\'un coup et emballe-les : ils se congèlent très bien.' },
  { id: 'r-wrap-dinde-avocat', name: 'Wrap dinde, avocat & crudités', cat: 'wrap', time: 5, tags: ['froid', 'rapide', 'lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Tortilla complète (wrap)', 120), R_('Blanc de dinde (tranches)', 100), R_('Avocat', 40), R_('Tomate', 60), R_('Salade verte', 20), R_('Moutarde', 5)],
    pantry: [],
    steps: ['Écrase l\'avocat avec la moutarde et tartine les tortillas.', 'Ajoute dinde, tomate et salade, puis roule.'],
    tip: 'L\'avocat écrasé remplace le beurre ou la mayonnaise.' },
  { id: 'r-wrap-pita', name: 'Pita poulet & sauce tzatziki', cat: 'wrap', time: 15, tags: ['lunchbox'], slots: ['lunch', 'dinner'],
    ing: [R_('Pain pita', 140), R_('Blanc de poulet cuit', 130), R_('Yaourt grec', 40), R_('Concombre', 60), R_('Tomate', 50), R_('Oignon rouge', 15)],
    pantry: ['Ail', 'Menthe', 'Paprika'],
    steps: ['Râpe un morceau de concombre, mélange-le au yaourt avec ail et menthe : c\'est le tzatziki.', 'Fais dorer le poulet au paprika.', 'Garnis les pitas tièdes de poulet, tomate, oignon et tzatziki.'],
    tip: 'Le goût du kebab, pour environ deux fois moins de calories.' },

  // ---------- Gratins & hachis ----------
  { id: 'r-gr-hachis', name: 'Hachis parmentier allégé', cat: 'gratin', time: 45, tags: ['batch', 'proteine'], slots: ['dinner', 'lunch'],
    ing: [R_('Steak haché 5 % (cuit)', 125), R_('Pomme de terre cuite', 250), R_('Lait demi-écrémé', 60), R_('Oignon rouge', 40), R_('Tomates concassées (boîte)', 50), R_('Emmental', 15)],
    pantry: ['Muscade', 'Sel, poivre'],
    steps: ['Cuis les pommes de terre 20 min, écrase-les avec le lait chaud et la muscade.', 'Fais revenir l\'oignon puis la viande, ajoute les tomates 5 min.', 'Viande au fond du plat, purée dessus, emmental, puis 20 min au four à 200 °C.'],
    tip: 'Le lait remplace le beurre dans la purée : même texture, bien plus léger. Prépare un grand plat pour 4 jours.' },
  { id: 'r-gr-hachis-pd', name: 'Hachis de patate douce au bœuf', cat: 'gratin', time: 45, tags: ['batch'], slots: ['dinner', 'lunch'],
    ing: [R_('Steak haché 5 % (cuit)', 110), R_('Patate douce cuite', 250), R_('Lait demi-écrémé', 40), R_('Oignon rouge', 30), R_('Épinards frais', 60), R_('Emmental', 15)],
    pantry: ['Cumin', 'Paprika'],
    steps: ['Cuis la patate douce 20 min à l\'eau et écrase-la avec le lait.', 'Fais revenir oignon, viande et épices, ajoute les épinards 1 min.', 'Monte le hachis, parsème d\'emmental et gratine 15 min à 200 °C.'],
    tip: 'Version plus riche en fibres et un peu sucrée du hachis classique.' },
  { id: 'r-gr-courgettes', name: 'Gratin de courgettes au poulet', cat: 'gratin', time: 40, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Courgette cuite', 300), R_('Blanc de poulet cuit', 130), R_('Lait demi-écrémé', 80), R_('Œuf entier', 60), R_('Emmental', 25), R_('Pain de mie complet', 50)],
    pantry: ['Ail', 'Herbes de Provence'],
    steps: ['Coupe les courgettes en rondelles, fais-les revenir 8 min pour qu\'elles rendent leur eau.', 'Mélange lait, œuf, ail et herbes.', 'Dans un plat : courgettes, poulet en dés, appareil lait-œuf, emmental. 25 min à 190 °C. Sers avec le pain.'],
    tip: 'Faire rendre l\'eau des courgettes avant évite un gratin qui baigne.' },
  { id: 'r-gr-choufleur', name: 'Gratin de chou-fleur & jambon', cat: 'gratin', time: 40, tags: [], slots: ['dinner'],
    ing: [R_('Chou-fleur', 300), R_('Pomme de terre cuite', 150), R_('Jambon blanc', 90), R_('Lait demi-écrémé', 150), R_('Emmental', 25)],
    pantry: ['Fécule de maïs (1 c. à soupe)', 'Muscade'],
    steps: ['Cuis chou-fleur et pommes de terre 12 min à l\'eau.', 'Béchamel légère : délaie la fécule dans le lait froid, chauffe en remuant jusqu\'à épaississement, ajoute la muscade.', 'Plat : légumes, jambon en lanières, béchamel, emmental. 20 min à 200 °C.'],
    tip: 'Une béchamel à la fécule, sans beurre ni farine : trois fois moins de gras.' },
  { id: 'r-gr-pates-thon', name: 'Gratin de pâtes au thon & tomate', cat: 'gratin', time: 30, tags: ['batch'], slots: ['dinner', 'lunch'],
    ing: [R_('Pâtes cuites', 200), R_('Thon au naturel', 100), R_('Tomates concassées (boîte)', 150), R_('Mozzarella', 40), R_('Oignon rouge', 30)],
    pantry: ['Basilic', 'Origan'],
    steps: ['Cuis les pâtes al dente.', 'Fais revenir l\'oignon, ajoute tomates et herbes 5 min, puis le thon émietté.', 'Mélange avec les pâtes, couvre de mozzarella, 15 min à 200 °C.'],
    tip: 'Le plat du placard : tout se garde des mois.' },
  { id: 'r-gr-lasagnes-courgette', name: 'Lasagnes de courgettes (sans pâtes)', cat: 'gratin', time: 50, tags: ['proteine', 'batch'], slots: ['dinner'],
    ing: [R_('Courgette cuite', 300), R_('Steak haché 5 % (cuit)', 120), R_('Tomates concassées (boîte)', 150), R_('Ricotta', 50), R_('Emmental', 20), R_('Pain de mie complet', 50)],
    pantry: ['Ail', 'Origan'],
    steps: ['Coupe les courgettes en longues tranches fines, grille-les 2 min par face.', 'Prépare une sauce bolognaise avec la viande, les tomates et l\'ail.', 'Alterne courgettes, bolognaise et ricotta, termine par l\'emmental. 30 min à 180 °C.'],
    tip: 'Les tranches de courgette remplacent les feuilles de lasagne : environ 250 kcal de moins par part.' },
  { id: 'r-gr-moussaka', name: 'Moussaka légère', cat: 'gratin', time: 55, tags: ['batch'], slots: ['dinner'],
    ing: [R_('Aubergine', 250), R_('Steak haché 5 % (cuit)', 120), R_('Tomates concassées (boîte)', 100), R_('Pomme de terre cuite', 150), R_('Oignon rouge', 40), R_('Yaourt grec', 50), R_('Emmental', 15)],
    pantry: ['Cannelle', 'Cumin', 'Ail'],
    steps: ['Coupe les aubergines en tranches, fais-les rôtir 20 min au four à 200 °C (sans huile, sur papier cuisson).', 'Fais revenir oignon et viande avec les épices, ajoute les tomates.', 'Superpose pommes de terre en rondelles, aubergines, viande. Couvre de yaourt et d\'emmental, 25 min à 190 °C.'],
    tip: 'Rôtir les aubergines au four évite qu\'elles boivent l\'huile comme une éponge.' },
  { id: 'r-gr-courgettes-farcies', name: 'Courgettes farcies viande & riz', cat: 'gratin', time: 45, tags: [], slots: ['dinner'],
    ing: [R_('Courgette cuite', 300), R_('Steak haché 5 % (cuit)', 110), R_('Riz basmati cuit', 120), R_('Tomates concassées (boîte)', 80), R_('Oignon rouge', 30), R_('Emmental', 15)],
    pantry: ['Herbes de Provence', 'Ail'],
    steps: ['Coupe les courgettes en deux, évide-les à la cuillère.', 'Fais revenir oignon, viande et chair des courgettes, ajoute riz et tomates.', 'Farcis, parsème d\'emmental, 30 min à 190 °C.'],
    tip: 'Avec des courgettes rondes, c\'est encore plus simple à farcir.' },
  { id: 'r-gr-quiche', name: 'Quiche sans pâte courgette & jambon', cat: 'gratin', time: 40, tags: ['batch'], slots: ['dinner', 'lunch'],
    ing: [R_('Œuf entier', 150), R_('Lait demi-écrémé', 100), R_('Courgette cuite', 200), R_('Jambon blanc', 60), R_('Emmental', 20), R_('Salade verte', 60)],
    pantry: ['Muscade', 'Poivre'],
    steps: ['Râpe les courgettes et presse-les pour retirer l\'eau.', 'Bats œufs et lait, ajoute courgettes, jambon en dés et emmental.', 'Verse dans un moule, 30 min à 180 °C. Sers avec la salade.'],
    tip: 'Sans pâte brisée, on économise environ 300 kcal par part. Se mange froide en gamelle.' },

  // ---------- Plats chauds ----------
  { id: 'r-plat-poelee-courgette', name: 'Poêlée courgettes, poulet & semoule', cat: 'plat', time: 20, tags: ['proteine'], slots: ['dinner', 'lunch'],
    ing: [R_('Blanc de poulet cuit', 140), R_('Courgette cuite', 200), R_('Poivron', 80), R_('Semoule cuite', 150), R_('Huile d\'olive', 8)],
    pantry: ['Ras el-hanout ou curry', 'Ail'],
    steps: ['Fais dorer le poulet en dés dans l\'huile.', 'Ajoute courgettes et poivron en dés, les épices, cuis 10 min.', 'Sers sur la semoule gonflée à l\'eau bouillante.'],
    tip: 'Une seule poêle, 20 minutes, pas de vaisselle.' },
  { id: 'r-plat-shakshuka', name: 'Ratatouille express & œufs pochés', cat: 'plat', time: 25, tags: ['vege'], slots: ['dinner', 'lunch', 'breakfast'],
    ing: [R_('Courgette cuite', 150), R_('Aubergine', 100), R_('Poivron', 100), R_('Tomates concassées (boîte)', 150), R_('Œuf entier', 120), R_('Pain de mie complet', 60), R_('Huile d\'olive', 5)],
    pantry: ['Cumin', 'Paprika', 'Ail'],
    steps: ['Fais revenir les légumes en dés 10 min dans l\'huile.', 'Ajoute tomates et épices, laisse mijoter 5 min.', 'Creuse deux puits, casse les œufs, couvre 6 min. Sers avec le pain.'],
    tip: 'Façon shakshuka : les œufs cuisent directement dans la sauce.' },
  { id: 'r-plat-butternut', name: 'Poulet, butternut rôtie & épinards', cat: 'plat', time: 35, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Blanc de poulet cuit', 150), R_('Courge butternut', 300), R_('Épinards frais', 60), R_('Huile d\'olive', 8), R_('Feta', 15)],
    pantry: ['Paprika fumé', 'Sel, poivre'],
    steps: ['Coupe la butternut en cubes (inutile de l\'éplucher), mélange avec l\'huile et le paprika, 25 min à 200 °C.', 'Poêle le poulet 6 min par face.', 'Fais tomber les épinards 1 min, sers le tout avec la feta émiettée.'],
    tip: 'La peau de la butternut se mange une fois rôtie : moins de travail, plus de fibres.' },
  { id: 'r-plat-curry-pois', name: 'Curry de pois chiches & épinards', cat: 'plat', time: 25, tags: ['vege', 'batch'], slots: ['dinner', 'lunch'],
    ing: [R_('Pois chiches cuits', 150), R_('Épinards frais', 80), R_('Tomates concassées (boîte)', 100), R_('Lait de coco léger', 60), R_('Riz basmati cuit', 150), R_('Oignon rouge', 30), R_('Skyr nature', 100)],
    pantry: ['Curry', 'Gingembre', 'Ail'],
    steps: ['Fais revenir l\'oignon avec les épices 2 min.', 'Ajoute pois chiches, tomates et lait de coco, mijote 10 min.', 'Incorpore les épinards à la fin, sers avec le riz et le skyr en raïta.'],
    tip: 'Le skyr remplace le yaourt de la raïta et ajoute des protéines au plat végétarien.' },
  { id: 'r-plat-wok', name: 'Wok de nouilles, poulet & légumes', cat: 'plat', time: 20, tags: ['proteine'], slots: ['dinner', 'lunch'],
    ing: [R_('Nouilles de riz cuites', 180), R_('Blanc de poulet cuit', 140), R_('Poivron', 80), R_('Carottes', 60), R_('Champignons de Paris', 60), R_('Sauce soja', 15), R_('Huile d\'olive', 5)],
    pantry: ['Gingembre', 'Ail', 'Sésame'],
    steps: ['Fais tremper les nouilles 5 min dans l\'eau bouillante.', 'Saisis le poulet à feu vif, puis les légumes en lamelles 4 min.', 'Ajoute nouilles et sauce soja, mélange 1 min.'],
    tip: 'Mieux qu\'un traiteur asiatique, et prêt plus vite qu\'une livraison.' },
  { id: 'r-plat-dinde-puree', name: 'Escalope de dinde, purée de chou-fleur & haricots verts', cat: 'plat', time: 25, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Escalope de dinde cuite', 160), R_('Chou-fleur', 250), R_('Lait demi-écrémé', 40), R_('Haricots verts', 150), R_('Emmental', 10), R_('Pain de mie complet', 50)],
    pantry: ['Muscade', 'Herbes'],
    steps: ['Cuis le chou-fleur 12 min, mixe-le avec le lait, l\'emmental et la muscade.', 'Cuis les haricots verts 8 min.', 'Poêle l\'escalope 4 min par face.'],
    tip: 'La purée de chou-fleur a le goût d\'une purée classique pour environ quatre fois moins de calories.' },
  { id: 'r-plat-filet-mignon', name: 'Filet mignon à la moutarde, pommes de terre & haricots', cat: 'plat', time: 35, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Filet mignon de porc cuit', 150), R_('Pomme de terre cuite', 200), R_('Haricots verts', 150), R_('Crème légère 15 %', 30), R_('Moutarde', 10)],
    pantry: ['Thym', 'Poivre'],
    steps: ['Fais dorer le filet mignon entier puis enfourne 20 min à 180 °C.', 'Cuis pommes de terre et haricots verts à la vapeur.', 'Sauce : crème et moutarde chauffées 1 min dans la poêle du filet.'],
    tip: 'Le filet mignon est l\'un des morceaux de porc les plus maigres.' },
  { id: 'r-plat-papillote', name: 'Papillote de cabillaud, poireaux & riz', cat: 'plat', time: 30, tags: ['proteine'], slots: ['dinner'],
    ing: [R_('Cabillaud cuit', 180), R_('Poireau', 150), R_('Riz basmati cuit', 150), R_('Crème légère 15 %', 20), R_('Citron (jus)', 10)],
    pantry: ['Aneth', 'Poivre'],
    steps: ['Émince les poireaux et fais-les fondre 8 min à la poêle.', 'Dans une feuille de papier cuisson : poireaux, poisson, crème, citron, aneth. Ferme bien.', '15 min à 200 °C. Sers avec le riz.'],
    tip: 'La papillote garde le poisson moelleux sans matière grasse.' },
  { id: 'r-plat-veloute', name: 'Velouté poireaux-pommes de terre & jambon', cat: 'plat', time: 30, tags: ['batch'], slots: ['dinner'],
    ing: [R_('Poireau', 200), R_('Pomme de terre cuite', 200), R_('Lait demi-écrémé', 100), R_('Jambon blanc', 60), R_('Crème légère 15 %', 20), R_('Pain de mie complet', 50)],
    pantry: ['Bouillon cube'],
    steps: ['Cuis poireaux et pommes de terre 20 min dans de l\'eau avec le bouillon.', 'Mixe avec le lait et la crème.', 'Sers avec le jambon en lanières et le pain grillé.'],
    tip: 'Un soir de flemme : une grande casserole fait 4 dîners.' }
);
